### ISSUE TITLE
Error reading SSH protocol banner This operation would block forever 

### ISSUE THREAD

**Issue by hokadiri** [gevent/gevent#816] opened 2016-06-05 18:25 UTC
* gevent version: 1.1.1
* Python version: 2.7.6
* Operating System: Red Hat Enterprise Linux Server release 6.7 (Santiago)

### Description:

```
// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?
I have a list of items. each item is a <host>:<cmd> combination. I want to use gevent queues with multiple workers to process each item asynchronously. by 'process' login to the <host> and run <cmd>  

I'm using fabric (version 1.11.1) to ssh to <host> and run <cmd>.

I get an ssh banner error

Error reading SSH protocol banner('This operation would block forever', <Hub at 0x14def50 epoll pending=0 ref=0 fileno=7>)

```

### What I've run:
Sample version of my script.
To run please replace: \<host1\>, \<cmd1\>, \<host2\>,\<cmd2\>, \<username\>, \<password\> with some valid items

I used:
\<cmd1\> = 'whoami'
\<cmd2\> = 'ls'

```
import gevent
import gevent.monkey;
# gevent.monkey.patch_thread()
gevent.monkey.patch_socket()
from fabric.api import run, sudo
from fabric.tasks import execute
from fabric.context_managers import quiet, settings
from fabric.state import env
from gevent.queue import Queue, Empty

tasks = Queue()
to_do = [{'host': '<host1>', 'task': '<cmd1>'}, {'host': '<host2>', 'task': '<cmd2>'}]
username = '<username>'
password = '<password>'

def do_work(cmd_str=None, use_sudo=False):
    with settings(quiet(), warn_only=True):
        if use_sudo:
            return sudo(cmd_str)
        else:
            return run(cmd_str)


def run_command(cmd_str, hosts, **kwargs):
    # import pdb;pdb.set_trace()
    try:
        env.pool_size = kwargs['pool_size']
    except KeyError:
        pass

    try:
        env.parallel = kwargs['parallel']
    except KeyError:
        pass

    try:
        env.no_agent = not kwargs['allow_agent']
    except KeyError:
        pass

    try:
        env.user = kwargs['username']
    except KeyError:
        pass

    try:
        env.password = kwargs['password']
    except KeyError:
        pass

    try:
        env.gateway = kwargs['gateway']
    except KeyError:
        pass

    try:
        use_sudo = kwargs['use_sudo']
    except KeyError:
        use_sudo = False

    output = execute(do_work, cmd_str=cmd_str, hosts=hosts, use_sudo=use_sudo)

    for host in hosts:
        print output[host].failed
        print output[host].return_code
        print output[host].succeeded
        ss = output[host]
        print ss
        print ss.split()
    # '''
    return output


def do_g_work(worker):
    use_sudo = True
    try:
        while not tasks.empty():
            task = tasks.get(timeout=1)
            print task, worker
            host = task['host']
            cmd_str = task['cmd']
            run_command(cmd_str, [host], gateway=None, allow_agent=False, username=username,
                        password=password, parallel=False, use_sudo=use_sudo)
            gevent.sleep(0)
    except Empty:
        print('Quitting time!')


def producer_function(iterable_item):
    for item in iterable_item:
        tasks.put(item)


if __name__ == "__main__":
    use_sudo = True
    gevent.spawn(producer_function, to_do).join()

    workers = [
        gevent.spawn(do_g_work, 'worker0'),
        gevent.spawn(do_g_work, 'worker1')
    ]

    gevent.joinall(workers)

```

Stack trace
```
$ python fab_test.py
{'host': '<host1>', 'task': '<cmd1>'} worker0
...
{'host': '<host2>', 'task': '<cmd2>'} worker1
...
Traceback (most recent call last):
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/transport.py", line 1864, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/packet.py", line 327, in readline
    buf += self._read_timeout(timeout)
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/packet.py", line 481, in _read_timeout
    x = self.__socket.recv(128)
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/gevent/_socket2.py", line 280, in recv
    self._wait(self._read_event)
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/gevent/_socket2.py", line 179, in _wait
    self.hub.wait(watcher)
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/gevent/hub.py", line 627, in wait
    result = waiter.get()
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/gevent/hub.py", line 875, in get
    return self.hub.switch()
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/gevent/hub.py", line 606, in switch
    return greenlet.switch(self)
LoopExit: ('This operation would block forever', <Hub at 0x14def50 epoll pending=0 ref=0 fileno=7>)
No handlers could be found for logger "paramiko.transport"
EXECPTION
<class 'paramiko.ssh_exception.SSHException'>
Traceback (most recent call last):
  File "fab_test.py", line 26, in run_command
    env.pool_size = kwargs['pool_size']
KeyError: 'pool_size'

Fatal error: Error reading SSH protocol banner('This operation would block forever', <Hub at 0x14def50 epoll pending=0 ref=0 fileno=7>)

Underlying exception:
    Error reading SSH protocol banner('This operation would block forever', <Hub at 0x14def50 epoll pending=0 ref=0 fileno=7>)

Aborting.
```

If I comment out the line:
```
gevent.monkey.patch_socket()
```

it works fine but it does it serially :(

**Comment by jamadden** [comment] 2016-06-05 18:31
I don't know anything about paramiko and whether it's supposed to work with gevent or not...it depends on what it's trying to do internally. But frequently such errors are the result of in incomplete monkey-patch. Have you tried `monkey.patch_all()` instead of patching an individual library?

**Comment by hokadiri** [comment] 2016-06-05 19:05
```monkey.patch_all() ``` works!
Thanks. So In general its better to monkey patch all instead of individual modules?

**Comment by hokadiri** [comment] 2016-06-05 19:19
Spoke too soon. it works if we're not using a proxy (gateway) to ssh to the hosts.
Changing from:
```
            run_command(cmd_str, [host], gateway=None, allow_agent=False, username=username,
                        password=password, parallel=False, use_sudo=use_sudo)
```
To:
```
            run_command(cmd_str, [host], gateway=<some_proxy_host>, allow_agent=False, username=username,
                        password=password, parallel=False, use_sudo=use_sudo)
```


Getting EOFError.
```
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/fabric/network.py", line 481, in connect
    client.connect(**kwargs)
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/client.py", line 341, in connect
    t.start_client()
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/transport.py", line 503, in start_client
    raise e

Traceback (most recent call last):
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/transport.py", line 1866, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/packet.py", line 327, in readline
    buf += self._read_timeout(timeout)
  File "/home/hkadiri/pssh_0_9/lib/python2.7/site-packages/paramiko/packet.py", line 483, in _read_timeout
    raise EOFError()
EOFError
No handlers could be found for logger "paramiko.transport"
ACTIVE:False
EXECPTION
<class 'paramiko.ssh_exception.SSHException'>
Traceback (most recent call last):
  File "fab_test.py", line 27, in run_command
    env.pool_size = kwargs['pool_size']
KeyError: 'pool_size'

Fatal error: Error reading SSH protocol banner

Underlying exception:
    Error reading SSH protocol banner

Aborting.
```

**Comment by jamadden** [comment] 2016-06-05 20:10
> So In general its better to monkey patch all instead of individual modules?

That's my preferred approach, yes. When gevent runs the standard library tests with monkey-patches, it always runs them with *all* monkey patches, not just those for the particular standard library being tested. You'd be surprised how many libraries that appear to only do networking, say, end up using Conditions or Locks or...

**Comment by jamadden** [comment] 2016-06-05 20:17
The EOF seems to be something deliberately raised when a timeout occurs reading from a socket. Putting a gateway in the middle presumably screws up the timing in some fashion that paramiko doesn't expect. 

I'm not sure this is a gevent *bug* per-se; paramiko may be trying to manually use non-blocking sockets or timeouts in a way that's not compatible with gevent. For example, gevent uses the most recent stdlib semantics for timeouts on sockets where the timeout is the total time, not just the time to send part of a chunk, closing a bug that exists in Python 2...but if paramiko inadvertently relied on that bug it might break.

I don't have any other input without knowing more than I'd care to about the internals of paramiko. Perhaps that team might have a suggestion on where to look further to narrow it down?

**Comment by pkittenis** [comment] 2016-07-05 16:01
This is caused by paramiko's use of a subprocess to initiate the proxy connection and fabric;s tight coupling with it. With gevent making subprocess async, that causes a race condition in fabric's code which expects the paramiko subprocess to run in the background and a dead lock which triggers the `This operation would block forever`. It is not a bug in gevent, no.

For a gevent using parallel SSH client library which uses paramiko for SSH protocol see [parallel-ssh](https://github.com/pkittenis/parallel-ssh) which also supports proxying/tunneling. It uses standard library sockets for proxying and does not suffer from the above. 

Note that it's an SSH client library, not a direct replacement for fabric.

**Closed** 2016-09-07 12:04 UTC
