### ISSUE TITLE
Upgrade 20.04, gevent always restart

### ISSUE THREAD

**Issue by Rukeith** [gevent/gevent#1608] opened 2020-05-12 03:40 UTC
* gevent version: 20.05.0
* Python version: Docker image python:3.7-slim
* Operating System: Docker image python:3.7-slim

### Description:

I just upgrade my gevent version from 1.4.0 to 20.5.0. I rebuild the docker image with the same script to start the server. The server always restart

```
[uWSGI] getting INI configuration from app.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue May 12 03:34:51 2020] ***
compiled with version: 8.3.0 on 12 May 2020 03:27:39
os: Linux-4.19.76-linuxkit #1 SMP Fri Apr 3 15:53:26 UTC 2020
nodename: ff561a78c2bd
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /usr/app
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
chdir() to /usr/app
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
- async cores set to 1000 - fd table size: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :5000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:33901 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
Python version: 3.7.7 (default, Apr 23 2020, 14:54:40)  [GCC 8.3.0]
Python main interpreter initialized at 0x55a42efba7d0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 21004928 bytes (20512 KB) for 1000 cores
*** Operational MODE: async ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55a42efba7d0 pid: 1 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 8, cores: 1000)
spawned uWSGI http 1 (pid: 9)
*** running gevent loop engine [addr:0x55a42da87bd0] ***
Python auto-reloader enabled
DAMN ! worker 1 (pid: 8) died :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 11)
*** running gevent loop engine [addr:0x55a42da87bd0] ***
Python auto-reloader enabled
DAMN ! worker 1 (pid: 11) died :( trying respawn ...
worker respawning too fast !!! i have to sleep a bit (2 seconds)...
Respawned uWSGI worker 1 (new pid: 13)
*** running gevent loop engine [addr:0x55a42da87bd0] ***
Python auto-reloader enabled
```

### What I've run:
Here is my dockerfile and app.ini

```Dockerfile
FROM python:3.7-slim
ENV FLASK_APP=flasky.py \
    FLASK_ENV=production
WORKDIR /usr/app
RUN apt-get update && \
    apt-get install -y gcc && \
    pip3 install pipenv
COPY Pipfile Pipfile.lock ./
RUN pipenv lock -r > requirements.txt && \
    pip3 install -r requirements.txt
COPY . .
CMD ["uwsgi", "--ini", "app.ini", "--py-autoreload", "1"]
```

```Ini
[uwsgi]
http = :5000
chdir = /usr/app
chmod-socket = 666
module = flasky
callable = app
master = true
processes = 1
vacuum = true
die-on-term = true
gevent = 1000
```

**Comment by jamadden** [comment] 2020-05-12 12:26
Thanks for the report. Looks like a duplicate of #1556

**Closed by jamadden** 2020-05-12 12:26 UTC
