### ISSUE TITLE
Error:gevent.hub.LoopExit: This operation would block forever

### ISSUE THREAD

**Issue by DYFeng** [gevent/gevent#368] opened 2014-01-05 08:35 UTC
I want to know more information about this execption.
How can it cause?
Do anyone have a simple demo can cause the execption?

**Comment by LaoLiulaoliu** [comment] 2015-01-04 10:28
```python
import gevent

class Event(object):
    def run(self):
        print('1 layer')
        gevent.joinall([gevent.spawn(self.sl) for i in range(5)])

    def sl(self):
        print('2 layer')
        gevent.joinall([gevent.spawn(self.tl) for i in range(2)])

    def tl(self):
        print('3 layer')


from gevent.pool import Pool

class EventPool(object):
    def __init__(self):
        self.poolsize = 5
        self.p = Pool(self.poolsize)

    def run(self):
        print('a layer')
        for i in range(self.poolsize):
            self.p.spawn(self.sl)
        self.p.join()

    def sl(self):
        print('b layer')
        for i in range(2):
            self.p.spawn(self.tl)

    def tl(self):
        print('c layer')

if __name__ == '__main__':
    Event().run()
    EventPool().run()
```

gevent.spawn nesting is all right, but pool nest spawn will cause this error?
May I ask why?
```python
# Traceback (most recent call last):
#   File "t.py", line 43, in <module>
#     EventPool().run()
#   File "t.py", line 31, in run
#     self.p.join()
#   File "/Users/bishop/.virtualenvs/husky/lib/python2.7/site-packages/gevent/pool.py", line 100, in join
#     self._empty_event.wait(timeout=timeout)
#   File "/Users/bishop/.virtualenvs/husky/lib/python2.7/site-packages/gevent/event.py", line 77, in wait
#     result = self.hub.switch()
#   File "/Users/bishop/.virtualenvs/husky/lib/python2.7/site-packages/gevent/hub.py", line 331, in switch
#     return greenlet.switch(self)
# gevent.hub.LoopExit: This operation would block forever
```

**Comment by raj454raj** [comment] 2015-10-04 21:36
Any updates on how to kill the threads? Please help.

**Comment by shell909090** [comment] 2015-10-13 14:14
@LaoLiulaoliu I think that maybe caused by limitation.
When this line `self.p.spawn(self.sl)` called, there will be 5 activate coroutines waiting for run, which just match the limitation of the pool. So, when one of them switched in, and get CPU. This line `self.p.spawn(self.tl)` will be runned, and will be blocked. After all 5 coroutines are blocked, this line `self.p.join()` will never get a result. So there raise an error.

**Comment by LaoLiulaoliu** [comment] 2015-10-22 05:55
@shell909090 Thanks for your explanations.

**Comment by hustlibraco** [comment] 2015-11-03 11:07
@LaoLiulaoliu 你池子只有5个大小，执行到self.p.spawn(self.tl)的时候又往同一个池子里加协程，当然5个sl全都会阻塞啦，然后程序就dead了~

**Comment by LaoLiulaoliu** [comment] 2015-11-17 07:10
@hustlibraco 很形象，谢谢啦 :)

**Comment by jamadden** [comment] 2016-10-27 12:52
Closing in triage for 1.2 because this question seems to have been answered and there have been no updates in a year.

**Closed by jamadden** 2016-10-27 12:52 UTC
