### ISSUE TITLE
Another PyPy 4.0.0 segfault

### ISSUE THREAD

**Issue by parasyte** [gevent/gevent#677] opened 2015-10-30 20:14 UTC
Hate to be the bearer of bad news, but there's another segfault on PyPy 4.0.0.

```
Oct 30 20:09:12 ip-172-16-34-220 kernel: [938442.261562] pypy[29304]: segfault at 50 ip 00007f78e1fe1ad4 sp 00007fff6c7ea820 error 4 in libpypy-c.so[7f78dfcdf000+2c71000]
```

I have a debug build now, so if I happen to catch it in the act, I'll have a core dump to look through.

**Comment by jamadden** [comment] 2015-10-30 20:56
Ok, thank you. Please let me know if you have any other clues.

**Comment by jamadden** [comment] 2015-10-31 00:31
I've been running networking stress tests and haven't reproduced a crash yet. I did notice a discrepancy in behaviour of a corner case that *maybe*, just *maybe* could result in a crash...or at least, weird behaviour. I fixed it in 1909383.

**Comment by parasyte** [comment] 2015-10-31 04:07
Thankfully, this segfault is pretty rare. I have one of our servers running the PyPy debug build with core dumps enabled. This machine was seeing about 1 segfault per day. We'll see whether it happens over the weekend.

Thanks for the followup patch.

**Comment by parasyte** [comment] 2015-10-31 19:58
I got some examples. Let me know how you would like to proceed... I can get you the debug build and a core file if you want to inspect these yourself. (Ubuntu 12.04) I won't be able to share the complete Python source code, but I could share snippets as necessary.

Each stack trace looks different, so these might be different bugs. Here they are (with paths anonymized):

https://gist.github.com/parasyte/c0bc45e9500e9033e569

**Comment by jamadden** [comment] 2015-11-01 16:35
Thanks for the examples. If I'm interpreting them correctly, two of them occur during garbage collection (one clearly dealing with a C extension, which for gevent could only be Semaphore (unless you enable c-ares)); one of them occurs executing `a[b] = c` and one executing something like `a < b`, and the remainder I'm not sure about.

There are traces of stacklet code and greenlet switching in a few of the traces. 

It's not clear to me how much of this, if any of it (aside from the possible cpyext issue) is gevent related, and how much of it might just be due to issues in the PyPy greenlet implementation that are just exercised by gevent. I don't see any of the `_cffi_...so` dylibs I would expect to see if the crash was during a gevent cffi callback, but that's not conclusive.

I'm not sure how to proceed with this information. Perhaps it's time to call in the PyPy devs for their reaction and opinions. Would you like to open issues or bring up on #pypy IRC (I'm usually there during the day, central time) or other?

**Comment by jamadden** [comment] 2015-12-10 17:37
@parasyte Does your application use stat watchers? I'm pretty sure I just found a crash with stat watchers.

**Comment by parasyte** [comment] 2015-12-10 19:48
@jamadden Not explicitly. I install about four signal handlers with gevent, though. Does that use stat watchers?

**Comment by jamadden** [comment] 2015-12-10 19:53
@parasyte Darn, I hoped that might have been it. gevent itself doesn't use stat watchers; signal watchers are their own watcher class.

**Comment by arigo** [comment] 2015-12-15 15:12
I'd have loved to have known about this bug report much earlier.

**Comment by jamadden** [comment] 2015-12-15 15:21
I'm sorry if it didn't get brought up. I guess the ball must have gotten dropped after [November 1st](https://github.com/gevent/gevent/issues/677#issuecomment-152842143).

**Comment by jamadden** [comment] 2016-03-16 16:31
Does this still occur with gevent 1.1 and pypy 5.0?

**Comment by parasyte** [comment] 2016-03-16 19:40
Nice! I didn't notice PyPy 5.0 was ready. Will update over the coming weeks.

**Comment by jamadden** [comment] 2016-10-27 12:59
Given that pypy is now at 5.4.1 and gevent is about to be at 1.2a1, I think it's probably time to close this in favor of a new issue with new stack traces if this is still reproducible under those versions.

**Closed by jamadden** 2016-10-27 12:59 UTC
Labels: pypy

**Comment by parasyte** [comment] 2018-01-05 23:18
Here's a quick update on this for archival purposes: PyPy 5.6 still segfaults infrequently. (Crashes are more frequent during bursts of network requests.) It is *not* caused by gevent. Given the info in the [backtraces](https://gist.github.com/parasyte/c0bc45e9500e9033e569) (also linked above), it has always looked like the crashes were somewhere in the garbage collector.

PyPy 5.8 fixed something very similar: https://bitbucket.org/pypy/pypy/issues/2531/parallel-requests-in-threads-segmentation Unfortunately we can't update past 5.6 yet because we're pinned to an old version of Ubuntu that is no longer supported. Newer builds don't work with the old libc.
