### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [gevent/gevent#1694] opened 2020-11-02 08:58 UTC
**Summary**
Installing gevent on aarch64 via pip using command "pip3 install gevent" tries to build wheel from source code.

**Problem description**
gevent doesn't have wheel for aarch64 on PyPI repository. So, while installing gevent via pip on aarch64, pip builds wheel for same resulting in it takes more time to install gevent. Making wheel available for aarch64 will benefit aarch64 users by minimizing gevent installation time.

**Expected Output**
Pip should be able to download gevent wheel from PyPI repository rather than building it from source code.

@gevent-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make gevent wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by jamadden** [comment] 2020-12-08 13:12
Duplicate of #1673

**Closed by jamadden** 2020-12-08 13:12 UTC
