### ISSUE TITLE
gevent installation hangs on Mavericks

### ISSUE THREAD

**Issue by YS-** [gevent/gevent#382] opened 2014-02-06 13:39 UTC
```
$ sudo ./setup.py install
Password:
running install
running bdist_egg
running egg_info
creating gevent.egg-info
writing requirements to gevent.egg-info/requires.txt
writing gevent.egg-info/PKG-INFO
writing top-level names to gevent.egg-info/top_level.txt
writing dependency_links to gevent.egg-info/dependency_links.txt
writing manifest file 'gevent.egg-info/SOURCES.txt'
reading manifest file 'gevent.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'gevent.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-intel/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.9-intel-2.7
creating build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/__init__.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/_threading.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/backdoor.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/baseserver.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/coros.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/event.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/fileobject.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/greenlet.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/hub.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/local.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/lock.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/monkey.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/os.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/pool.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/pywsgi.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/queue.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/resolver_ares.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/resolver_thread.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/select.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/server.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/socket.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/ssl.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/subprocess.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/thread.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/threading.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/threadpool.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/timeout.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/util.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/win32util.py -> build/lib.macosx-10.9-intel-2.7/gevent
copying gevent/wsgi.py -> build/lib.macosx-10.9-intel-2.7/gevent
running build_ext
Running '/bin/sh /Users/orw/Downloads/gevent-1.0/libev/configure > configure-output.txt' in /Users/orw/Downloads/gevent-1.0/build/temp.macosx-10.9-intel-2.7/libev
building 'gevent.core' extension
creating build/temp.macosx-10.9-intel-2.7/gevent
cc -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -U__llvm__ -arch x86_64 -arch i386 -pipe -DLIBEV_EMBED=1 -DEV_COMMON= -DEV_CHECK_ENABLE=0 -DEV_CLEANUP_ENABLE=0 -DEV_EMBED_ENABLE=0 -DEV_PERIODIC_ENABLE=0 -Ibuild/temp.macosx-10.9-intel-2.7/libev -Ilibev -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c gevent/gevent.core.c -o build/temp.macosx-10.9-intel-2.7/gevent/gevent.core.o
In file included from gevent/gevent.core.c:302:
In file included from gevent/libev.h:2:
libev/ev.c:467:48: warning: '/*' within block comment [-Wcomment]
/*#define MIN_INTERVAL  0.00000095367431640625 /* 1/2**20, good till 2200 */
                                               ^
libev/ev.c:1311:31: warning: 'extern' variable has an initializer
  EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                              ^
libev/ev.c:1482:7: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ANPENDING, pendings [pri], pendingmax [pri], w_->pending, EMPTY2);
      ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:1493:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (W, rfeeds, rfeedmax, rfeedcnt + 1, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:1620:7: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (int, fdchanges, fdchangemax, fdchangecnt, EMPTY2);
      ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
In file included from gevent/gevent.core.c:302:
In file included from gevent/libev.h:2:
In file included from libev/ev.c:2168:
libev/ev_kqueue.c:50:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (struct kevent, kqueue_changes, kqueue_changemax, kqueue_changecnt, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
In file included from gevent/gevent.core.c:302:
In file included from gevent/libev.h:2:
In file included from libev/ev.c:2174:
libev/ev_poll.c:66:7: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (struct pollfd, polls, pollmax, pollcnt, EMPTY2);
      ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:3332:34: warning: '&' within '|' [-Wbitwise-op-parentheses]
  fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                       ~~~~~~~~~~^~~~~~~~~~~~~ ~
libev/ev.c:3332:34: note: place parentheses around the '&' expression to silence this warning
  fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                                 ^
                       (                      )
libev/ev.c:3371:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ANHE, timers, timermax, ev_active (w) + 1, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4041:5: warning: unused variable 'ocur_' [-Wunused-variable]
    array_needsize (ev_idle *, idles [ABSPRI (w)], idlemax [ABSPRI (w)], active, EMPTY2);
    ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4081:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ev_prepare *, prepares, preparemax, preparecnt, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4266:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ev_fork *, forks, forkmax, forkcnt, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4349:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ev_async *, asyncs, asyncmax, asynccnt, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
gevent/gevent.core.c:36178:19: warning: expression result unused [-Wunused-value]
    PyObject_INIT(o, t);
    ~~~~~~~~~~~~~~^~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/objimpl.h:164:69: note: expanded from macro
      'PyObject_INIT'
    ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
                                                                    ^
14 warnings generated.
In file included from gevent/gevent.core.c:302:
In file included from gevent/libev.h:2:
libev/ev.c:467:48: warning: '/*' within block comment [-Wcomment]
/*#define MIN_INTERVAL  0.00000095367431640625 /* 1/2**20, good till 2200 */
                                               ^
libev/ev.c:1311:31: warning: 'extern' variable has an initializer
  EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                              ^
libev/ev.c:1482:7: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (ANPENDING, pendings [pri], pendingmax [pri], w_->pending, EMPTY2);
      ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:1493:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (W, rfeeds, rfeedmax, rfeedcnt + 1, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:1620:7: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (int, fdchanges, fdchangemax, fdchangecnt, EMPTY2);
      ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
In file included from gevent/gevent.core.c:302:
In file included from gevent/libev.h:2:
In file included from libev/ev.c:2168:
libev/ev_kqueue.c:50:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (struct kevent, kqueue_changes, kqueue_changemax, kqueue_changecnt, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
In file included from gevent/gevent.core.c:302:
In file included from gevent/libev.h:2:
In file included from libev/ev.c:2174:
libev/ev_poll.c:66:7: warning: unused variable 'ocur_' [-Wunused-variable]
      array_needsize (struct pollfd, polls, pollmax, pollcnt, EMPTY2);
      ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:3332:34: warning: '&' within '|' [-Wbitwise-op-parentheses]
  fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                       ~~~~~~~~~~^~~~~~~~~~~~~ ~
libev/ev.c:3332:34: note: place parentheses around the '&' expression to silence this warning
  fd_change (EV_A_ fd, w->events & EV__IOFDSET | EV_ANFD_REIFY);
                                 ^
                       (                      )
libev/ev.c:3371:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ANHE, timers, timermax, ev_active (w) + 1, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4041:5: warning: unused variable 'ocur_' [-Wunused-variable]
    array_needsize (ev_idle *, idles [ABSPRI (w)], idlemax [ABSPRI (w)], active, EMPTY2);
    ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4081:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ev_prepare *, prepares, preparemax, preparecnt, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4266:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ev_fork *, forks, forkmax, forkcnt, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
libev/ev.c:4349:3: warning: unused variable 'ocur_' [-Wunused-variable]
  array_needsize (ev_async *, asyncs, asyncmax, asynccnt, EMPTY2);
  ^
libev/ev.c:1444:22: note: expanded from macro 'array_needsize'
      int ecb_unused ocur_ = (cur);                                     \
                     ^
gevent/gevent.core.c:36178:19: warning: expression result unused [-Wunused-value]
    PyObject_INIT(o, t);


    ~~~~~~~~~~~~~~^~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/objimpl.h:164:69: note: expanded from macro
      'PyObject_INIT'
    ( Py_TYPE(op) = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
                                                                    ^
14 warnings generated.
```
---
it hangs here.

**Comment by jamadden** [comment] 2015-07-08 18:30
Is this reproducible with master or gevent1.1a1? libev has been upgraded since then. I'm unable to reproduce a hang on OS X.

**Comment by jamadden** [comment] 2015-10-16 19:45
Closing because of libev updates, and because of OS X updates, and because we distribute binary wheels for OS X on PyPI now so most users probably won't be compiling it themselves. Please open a new issue if you still see failures with current code on current operating systems.

**Closed by jamadden** 2015-10-16 19:45 UTC
Labels: question
