### ISSUE TITLE
While true in main thread causes app to hang.

### ISSUE THREAD

**Issue by Hacksawfred3232** [gevent/gevent#1975] opened 2023-07-18 16:07 UTC
* gevent version: 23.7.0, using Pip3 from Pypi
* Python version: Python 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] on linux
* Operating System: Debian 11 bullseye GNU/Linux on a x86_64 system

### Description:

Certain apps that I want to build - more specfically, a bottle framework app that uses gevent websockets and also contains a server-side console for control - requires "while true" to be executed in the main thread in order to work properly. Unfortuantly, this doesn't seem to be a viable option, since attempting to do this causes Python to hang. If it's possible to fix, then this problem should be fixed. If not, I would like an explaination into why this can't be fixed, and what alternative way is required to fulfil the task I described. 

### What I've run:

The following is test code that can replicate the problem.

```python
import threading
import time
from gevent import monkey
monkey.patch_all()
# If the two lines above are present, when code hits "while True", execution stops?

def ExecFunc(StopFlag: threading.Lock):
    while StopFlag.locked() != True:
        time.sleep(0.5)
        print("Hello World!")

StopSign = threading.Lock()
ThreadingTh = threading.Thread(target=ExecFunc,args=[StopSign])
ThreadingTh.start()
try:
    while True:
        pass
except KeyboardInterrupt:
    pass
StopSign.acquire()
ThreadingTh.join()
```

Edit: While commenting out time.sleep _does fix the problem,_ it's not a solution. Since a backend call to a database or a simliar function could behave simliarly to time.sleep and cause the same problem.

**Comment by arcivanov** [comment] 2023-07-18 21:10
That's the expected behavior. At no point does the while loop relinquish control to allow other greenlets to run.
You can use 

```
while True:
    sleep(0.01)
```

Or in the alternative `ThreadingTh.join()`.

**Comment by Hacksawfred3232** [comment] 2023-07-19 07:31
> That's the expected behavior. At no point does the while loop relinquish control to allow other greenlets to run. You can use
> 
> ```
> while True:
>     sleep(0.01)
> ```
> 
> Or in the alternative `ThreadingTh.join()`.

I see. Question: Python's regular "thread coordinator" is able to handle this condition. Using that sleep function does work around the issue, but I didn't see it as a solution because it implies that no other python library that I later import will cause the same issue - though I guess that's what the monkey patch function is for.

What does gevent's "thread coordinator" do differently than the standard inbuilt Python one?

**Comment by arcivanov** [comment] 2023-07-19 14:09
There is no "thread coordinator" or scheduler in regular CPython. The loop in `ceval` checks volatile flag prior to each instruction and the thread voluntarily signals to the other waiting threads to wake up, relinquishes the GIL and acquires a waiter to get in a queue.

Gevent is COOPERATIVE multitasking. The `ThreadingTh` is not a thread (you have monkey-patched!), it's a greenlet masquerading behind the threading API, and you need to cooperate to relinquish control.

Even if you were not using gevent at all a `while True` waiter is a superbly bad idea, due to you just spinning endlessly burning energy and CPU cycles while doing absolutely nothing except producing heat and sadness.

**Comment by Hacksawfred3232** [comment] 2023-07-20 22:02
> There is no "thread coordinator" or scheduler in regular CPython. The loop in `ceval` checks volatile flag prior to each instruction and the thread voluntarily signals to the other waiting threads to wake up, relinquishes the GIL and acquires a waiter to get in a queue.

So... what's python doing by default that makes the `while True` loop not block `ThreadingTh`?

> Gevent is COOPERATIVE multitasking. The `ThreadingTh` is not a thread (you have monkey-patched!), it's a greenlet masquerading behind the threading API, and you need to cooperate to relinquish control.

So - unless I'm wrong in this assumption - gevent is turning a multi-threaded app back into a single-threaded app, by patching out the "multi-threading" part. That kinda defeats the purpose of multi-threading applications that a well-coded bottle framework app relies on. Which makes it weird that bottle is suggesting a gevent websockets implementation _for what needs to be multi-threaded in order to not choke on a single client request_

> Even if you were not using gevent at all a `while True` waiter is a superbly bad idea, due to you just spinning endlessly burning energy and CPU cycles while doing absolutely nothing except producing heat and sadness.

So making a "SafePass" or "SafeNoOp" lambda function that I can reference later which runs `sleep(0.01)` will most likely be a must when making code with gevent. I can't use a high number like 0.01 though. Because if I do, I probs will run into some stupid error where a program misses a signal from the OS. I have run into applications that have done that before, though I don't remeber the name of said apps. It would most likely have to be 0.00005 or 0.00001, which I have seen working with the test code.

**Comment by jamadden** [comment] 2023-07-20 22:58
> So - unless I'm wrong in this assumption 

You are, but probably not for the reasons you may think. (Specifically, when the code is written correctly to work with threads, it will also work correctly with gevent. Your code was not correct --- and yes, even with Python's preemptive threads, correct code will perform better than yours, although you may not be able to see it on a stopwatch. Less specifically, there are ways to run multiple native --- preemptive --- threads and/or multiple gevent loops in the same process at the same time, and to control what APIs get patched.)

> So making a "SafePass" or "SafeNoOp" lambda function that I can reference later which runs sleep(0.01) will most likely be a must when making code with gevent. 

None of that is correct. You seem to have misunderstood @arcivanov when he wrote "Even if you were not using gevent at all a while True waiter is a superbly bad idea, due to you just spinning endlessly burning energy and CPU cycles while doing absolutely nothing except producing heat and sadness."

Busy loops (in Python) are a bad idea. Cooperative or preemptive, it doesn't matter: Bad idea. Code like your example: Bad code.

Perhaps you're a newcomer to threads, but this is why objects like condition variables and events exist, and why they (and even locks) have methods like `wait(timeout=None)`. Use those things correctly, and both your preemptive and cooperative programs will behave better.

At any rate, this is not a bug or issue in gevent. I'm going to close this ticket. Unless you would like to propose documentation updates to help clarify the things we're explaining to you for others, in which case, please re-open or submit a PR.

**Closed by jamadden** 2023-07-20 22:58 UTC
