### ISSUE TITLE
urllib2-based tests fail due to timeouts

### ISSUE THREAD

**Issue by czarkoff** [gevent/gevent#737] opened 2016-02-10 09:19 UTC
On OpenBSD -current with python 2.7.11 some urllib2 tests for 1.1rc3 fail due to timeouts (see line 379 and onwards in [test log](http://pastebin.com/ifeFEWWW)). There are other similar failures down the log.

P.S.: tests in *test___example_servers.py* don't fail if I remove explicit timeouts on lines [26](https://github.com/gevent/gevent/blob/5fd0f6ef5558849b4e15349f385049d7dbc64375/greentest/test___example_servers.py#L26) and [28](https://github.com/gevent/gevent/blob/5fd0f6ef5558849b4e15349f385049d7dbc64375/greentest/test___example_servers.py#L28). I am not sure what exactly is tested here though.

**Comment by jamadden** [comment] 2016-02-10 12:44
Indeed, gevent's entire test suite is highly sensitive to timing issues. You can run into problems due to load, or simply different tolerances in the system's clock accuracy/jitter, process scheduling, etc.

Depending on *why* the test failures are an issue for you, I can imagine a couple paths forward. 

* If you're trying to hack on gevent itself, you can take a similar approach to what we do for Windows (AppVeyor) and relax the tolerances in the test cases themselves when running on that particular platform (but note that nothing like that is currently done for `test__example_servers.py` because it doesn't run on windows). I would review PRs that do that.
* A simpler solution, possibly most useful if you're trying to package gevent for a package manager, and you can't have it simply *skip* the tests (gevent isn't released until it gets a green build on Windows, OS X, and Linux), would be a PR that adds the list of failing tests you see to `known_failures.py` (again, for this platform).

Both solutions are likely to become outdated, though. We have continuous integration running for Linux (via TravisCI) and Windows (via AppVeyor) and we are committed to distributing binary wheels for OS X (we could have CI on Travis for OS X, but that's my primary development platform so it's currently not as necessary), so the tests are always running on those platforms. But we don't have a CI for *BSD; without that, things are likely to break between releases.

**Comment by czarkoff** [comment] 2016-02-10 13:54
I somehow ended up being a gevent port maintainer on OpenBSD, and I am using tests to make sure everything works. I can skip tests, or just ignore failures, but I am interested in reliable test suite because I want to make sure I am not committing broken update to ports...

**Comment by jamadden** [comment] 2016-02-10 14:15
I'm happy to review PRs that adjust timeouts on your platform to make the tests pass for you; it'd be great to have tests passing on as many platforms as possible. But I currently have no way to test or verify correctness myself.

I'd be even happier if there was a *BSD CI service that could be integrated into github like Travis and Appveyor.

**Comment by jamadden** [comment] 2016-03-05 19:40
It just occurred to me: our Windows CI service (Appveyor) has a record of producing timeouts and has a great deal of clock jitter, making the runs less reproducible. As a consequence, many of the tests already adapt themselves for that environment by relaxing timing constraints. That way, the functionality is still tested to be correct, albeit with looser timing guarantees.

We detect we're on appveyor by the presence of the APPVEYOR environment variable. It's possible that setting that variable while you run tests might resolve many of your issues.

**Comment by czarkoff** [comment] 2016-03-05 23:37
Maybe it would be a good idea to enable this behavior on by default and allow forcing stricter timeouts with something like TEST_TIMEOUTS=tight environment variable?  Packages are normally built on busy machines...

**Comment by jamadden** [comment] 2016-03-05 23:45
I would imagine the Travis containers to be pretty busy ([300,000+ builds per day, 2000 concurrently](https://blog.travis-ci.com/2016-02-05-happy-fifth-birthday-travis-ci) and we don't have this problem there. It seems much more related to the particular OS's timing primitives.

I do think strict timing should be the default. Otherwise, when someone tries to run the tests, they'll have no way of knowing whether their particular platform will be able to deliver the expected accuracy: test failures are the thing that lets you know.

**Comment by jamadden** [comment] 2016-10-26 21:02
Closing in triage for 1.2a1 and because there haven't been any updates since March (though I suspect a pending release might spur interest in this again). Feel free to reopen if there is new info or discussion.

**Closed by jamadden** 2016-10-26 21:02 UTC
Labels: enhancement
