### ISSUE TITLE
Expected in: flat namespace

### ISSUE THREAD

**Issue by jumping** [gevent/gevent#268] opened 2013-04-07 07:19 UTC
95:~ jumping$ python
Python 2.7.2 (default, Oct 11 2012, 20:14:37)
[GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/gevent-0.13.8-py2.7-macosx-10.8-intel.egg/gevent/__init__.py", line 40, in <module>
    from gevent import core
ImportError: dlopen(/Library/Python/2.7/site-packages/gevent-0.13.8-py2.7-macosx-10.8-intel.egg/gevent/core.so, 2): Symbol not found: _event_global_current_base_
  Referenced from: /Library/Python/2.7/site-packages/gevent-0.13.8-py2.7-macosx-10.8-intel.egg/gevent/core.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/gevent-0.13.8-py2.7-macosx-10.8-intel.egg/gevent/core.so
>>>

**Comment by jamadden** [comment] 2015-07-10 22:46
Closing in triage for gevent 1.1 because the issue is over two years old with no updates and on an unsupported version of gevent. Please feel free to open another issue if you have a problem with gevent 1.0.2 or gevent 1.1a2.

**Closed by jamadden** 2015-07-10 22:46 UTC
