### ISSUE TITLE
Multiple test failures in 1.1b6

### ISSUE THREAD

**Issue by jlec** [gevent/gevent#682] opened 2015-11-05 14:40 UTC
```python
 ======================================================================
  FAIL: test__1_2_3_400__gethostbyaddr (__main__.TestBadIP)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "test__socket_dns.py", line 187, in test4
      self._test('gethostbyaddr', x)
    File "test__socket_dns.py", line 217, in _test
      self.assertEqualResults(real_result, gevent_result, func, args)
    File "test__socket_dns.py", line 255, in assertEqualResults
      self.assertEqual((msg, gevent_result), (msg, real_result))
  AssertionError: Tuples differ: ("get[19 chars]00')", BlockingIOError(11, 'Resource temporarily unavailable')) != ("get[19 chars]00')", gaierror(-2, 'Name or service not known'))
  
  First differing element 1:
  [Errno 11] Resource temporarily unavailable
  [Errno -2] Name or service not known
  
  + ("gethostbyaddr('1.2.3.400')", gaierror(-2, 'Name or service not known'))
  - ("gethostbyaddr('1.2.3.400')",
  -  BlockingIOError(11, 'Resource temporarily unavailable'))
  
  ======================================================================
  FAIL: test__xxxxxxxxxxxx__gethostbyaddr (__main__.TestBadName)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "test__socket_dns.py", line 187, in test4
      self._test('gethostbyaddr', x)
    File "test__socket_dns.py", line 217, in _test
      self.assertEqualResults(real_result, gevent_result, func, args)
    File "test__socket_dns.py", line 255, in assertEqualResults
      self.assertEqual((msg, gevent_result), (msg, real_result))
  AssertionError: Tuples differ: ("get[22 chars]xx')", BlockingIOError(11, 'Resource temporarily unavailable')) != ("get[22 chars]xx')", gaierror(-2, 'Name or service not known'))
  
  First differing element 1:
  [Errno 11] Resource temporarily unavailable
  [Errno -2] Name or service not known
  
  + ("gethostbyaddr('xxxxxxxxxxxx')", gaierror(-2, 'Name or service not known'))
  - ("gethostbyaddr('xxxxxxxxxxxx')",
  -  BlockingIOError(11, 'Resource temporarily unavailable'))
  
  ======================================================================
  FAIL: test__ip6_localhost__gethostbyaddr (__main__.TestLocalhost)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "test__socket_dns.py", line 187, in test4
      self._test('gethostbyaddr', x)
    File "test__socket_dns.py", line 217, in _test
      self.assertEqualResults(real_result, gevent_result, func, args)
    File "test__socket_dns.py", line 255, in assertEqualResults
      self.assertEqual((msg, gevent_result), (msg, real_result))
  AssertionError: Tuples differ: ("get[23 chars]st')", BlockingIOError(11, 'Resource temporarily unavailable')) != ("get[23 chars]st')", gaierror(-2, 'Name or service not known'))
  
  First differing element 1:
  [Errno 11] Resource temporarily unavailable
  [Errno -2] Name or service not known
  
  + ("gethostbyaddr('ip6-localhost')", gaierror(-2, 'Name or service not known'))
  - ("gethostbyaddr('ip6-localhost')",
  -  BlockingIOError(11, 'Resource temporarily unavailable'))
  
  ======================================================================
  FAIL: test__nonexistentxxxyyy__gethostbyaddr (__main__.TestNonexistent)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "test__socket_dns.py", line 187, in test4
      self._test('gethostbyaddr', x)
    File "test__socket_dns.py", line 217, in _test
      self.assertEqualResults(real_result, gevent_result, func, args)
    File "test__socket_dns.py", line 255, in assertEqualResults
      self.assertEqual((msg, gevent_result), (msg, real_result))
  AssertionError: Tuples differ: ("get[27 chars]yy')", BlockingIOError(11, 'Resource temporarily unavailable')) != ("get[27 chars]yy')", gaierror(-2, 'Name or service not known'))
  
  First differing element 1:
  [Errno 11] Resource temporarily unavailable
  [Errno -2] Name or service not known
  
    ("gethostbyaddr('nonexistentxxxyyy')",
  -  BlockingIOError(11, 'Resource temporarily unavailable'))
  +  gaierror(-2, 'Name or service not known'))
  
  ======================================================================
  FAIL: test_notexistent_dot_com (__main__.Test_getaddrinfo)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/var/tmp/portage/dev-python/gevent-1.1_beta6/work/gevent-1.1b6/greentest/greentest.py", line 213, in wrapped
      return method(self, *args, **kwargs)
    File "/var/tmp/portage/dev-python/gevent-1.1_beta6/work/gevent-1.1b6/greentest/greentest.py", line 202, in wrapped
      return method(self, *args, **kwargs)
    File "/var/tmp/portage/dev-python/gevent-1.1_beta6/work/gevent-1.1b6/greentest/greentest.py", line 88, in wrapped
      return method(self, *args, **kwargs)
    File "test__socket_dns.py", line 391, in test_notexistent_dot_com
      self._test_getaddrinfo('sdfsdfgu5e66098032453245wfdggd.com', 80)
    File "test__socket_dns.py", line 373, in _test_getaddrinfo
      self._test('getaddrinfo', *args)
    File "test__socket_dns.py", line 217, in _test
      self.assertEqualResults(real_result, gevent_result, func, args)
    File "test__socket_dns.py", line 255, in assertEqualResults
      self.assertEqual((msg, gevent_result), (msg, real_result))
  AssertionError: Tuples differ: ("get[46 chars] 80)", BlockingIOError(11, 'Resource temporarily unavailable')) != ("get[46 chars] 80)", gaierror(-2, 'Name or service not known'))
  
  First differing element 1:
  [Errno 11] Resource temporarily unavailable
  [Errno -2] Name or service not known
  
    ("getaddrinfo('sdfsdfgu5e66098032453245wfdggd.com', 80)",
  -  BlockingIOError(11, 'Resource temporarily unavailable'))
  +  gaierror(-2, 'Name or service not known'))
  
  ======================================================================
  FAIL: test_notexistent_tld (__main__.Test_getaddrinfo)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/var/tmp/portage/dev-python/gevent-1.1_beta6/work/gevent-1.1b6/greentest/greentest.py", line 213, in wrapped
      return method(self, *args, **kwargs)
    File "/var/tmp/portage/dev-python/gevent-1.1_beta6/work/gevent-1.1b6/greentest/greentest.py", line 202, in wrapped
      return method(self, *args, **kwargs)
    File "/var/tmp/portage/dev-python/gevent-1.1_beta6/work/gevent-1.1b6/greentest/greentest.py", line 88, in wrapped
      return method(self, *args, **kwargs)
    File "test__socket_dns.py", line 388, in test_notexistent_tld
      self._test_getaddrinfo('myhost.mytld', 53)
    File "test__socket_dns.py", line 373, in _test_getaddrinfo
      self._test('getaddrinfo', *args)
    File "test__socket_dns.py", line 217, in _test
      self.assertEqualResults(real_result, gevent_result, func, args)
    File "test__socket_dns.py", line 255, in assertEqualResults
      self.assertEqual((msg, gevent_result), (msg, real_result))
  AssertionError: Tuples differ: ("get[24 chars] 53)", BlockingIOError(11, 'Resource temporarily unavailable')) != ("get[24 chars] 53)", gaierror(-2, 'Name or service not known'))
  
  First differing element 1:
  [Errno 11] Resource temporarily unavailable
  [Errno -2] Name or service not known
  
  + ("getaddrinfo('myhost.mytld', 53)", gaierror(-2, 'Name or service not known'))
  - ("getaddrinfo('myhost.mytld', 53)",
  -  BlockingIOError(11, 'Resource temporarily unavailable'))
  
  ----------------------------------------------------------------------
  Ran 120 tests in 2.492s
  
  FAILED (failures=6)

```

**Comment by jlec** [comment] 2015-11-05 14:40
This happens with python3

**Comment by jamadden** [comment] 2015-11-05 14:54
Those all seem to come from [test__socket_dns](https://github.com/gevent/gevent/blob/master/greentest/test__socket_dns.py) which is [known to have issues](https://github.com/gevent/gevent/blob/master/known_failures.py#L133) on Python 3, so it should not result in the actual testrunner failing.

I would review a PR to correct the issues, but because the tests must run on Python 2.6, 2.7, 3.3, 3.4, and 3.5 as well as PyPy and on Travis CI and AppVeyor (Windows) that's not necessarily trivial. For the moment, Python 2.7 on Travis is the "primary" platform and some of the more involved tests (like this one) are simply marked as currently expected to fail on different platforms.

**Comment by jamadden** [comment] 2016-03-29 23:10
At least Python 2.6 has been dropped :) See also #774 .

**Comment by zt-initech** [comment] 2016-07-24 19:11
I think this is not a DNS code issue. This is a EAGAIN (errno 11) issue.

My very simple code, which is basically this (anonymized):

```python
import socket
import gevent
from gevent.monkey import patch_all
patch_all()

def foo():
    sock = socket.create_connection(('my_ip', my_port))
    conn = sock.makefile("rwb", 0)
    # data_packets is list of 1000 byte strings, each 1000 bytes
    for data_packet in data_packets:
        conn.write(data_packet)

job = gevent.spawn(foo)
job.start()
job.join()
```

fails on cpython3.4 after EAGAIN (Errno 11).

```
Traceback (most recent call last):
  File "/home/appuser/qa/local/lib64/python3.4/site-packages/gevent/_socket3.py", line 372, in send
    return _socket.socket.send(self._sock, data, flags)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/appuser/qa/local/lib64/python3.4/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "foo-client.py", line 105, in foo
    conn.write(data_packet)
  File "/usr/lib64/python3.4/socket.py", line 394, in write
    return self._sock.send(b)
  File "/home/appuser/qa/local/lib64/python3.4/site-packages/gevent/_socket3.py", line 378, in send
    return _socket.socket.send(self._sock, data, flags)
BrokenPipeError: [Errno 32] Broken pipe
<Greenlet at 0x7f170f870df0: foo()> failed with BrokenPipeError
```

tcpdump shows some data is silently not sent, that's why the server closed the connection.
If the client sends slowly and never gets to EAGAIN, it works fine on cpython3.4 too.

The code works fine on cpython 2.7.10.
`gevent==1.1.2`
`greenlet==0.4.10`
on amazon ec2 with amazon linux.

**Comment by jamadden** [comment] 2016-10-27 12:20
Closing in favor of/as a duplicate of #774.

**Closed by jamadden** 2016-10-27 12:20 UTC
Labels: enhancement, python3
