### ISSUE TITLE
incompatibility with py2exe for python27-64bit

### ISSUE THREAD

**Issue by mprosperi** [gevent/gevent#707] opened 2015-12-17 09:03 UTC
gevent doesn't find module 'path' if packaged with py2exe on windows. A workaround is to use "bundle_files": 3 in py2exe script but this is supported only on 32bit platform. The solutions should be to put in os.py this line:
path = os.path

**Comment by jamadden** [comment] 2015-12-17 10:48
Can you be more explicit? For example, post an actual error? I don't understand what you mean, and `gevent.os` doesn't use the `os.path` module.

**Comment by mprosperi** [comment] 2015-12-17 11:29
the problem is this (also present in gevent1.1rc1):
http://stackoverflow.com/questions/23452239/how-to-use-py2exe-packing-pythongevent-program-into-exe-file
If you use py2exe with python 64 bit you cannot use "bundle_files": 1 as suggested in SO answer (in my first post I wrongly wrote "bundle_files": 3) because is not supported.
Seems that py2exe doesn't find the module 'os.path' because of gevent.os.
If I add:
path=os.path in gevent's os.py file py2exe works fine

**Comment by jamadden** [comment] 2015-12-17 11:31
Doesn't that really seem like a bug in py2exe? Clearly `gevent.os` and `os` are *not* the same thing.

**Comment by jamadden** [comment] 2015-12-17 12:07
In #181 it was indicated that importing `gevent.os` instead of `os` was a bug in bbfreeze

**Comment by mprosperi** [comment] 2015-12-17 13:18
yes, it is a bug in py2exe, but to be pragmatic: gevent 0.13.8 works fine with this py2exe bug without relying on it to be solved. If gevent1.1 could do the same would be a plus for gevent users. Also: gevent is coming out with a new release and py2exe is not AFAIK. If you think that is better to do nothing in gevent then I'll use my workaround

**Comment by jamadden** [comment] 2015-12-17 13:22
0.13.8 is *ancient*; the 1.0 series dates to 2011. Did this work with 1.0?

**Comment by mprosperi** [comment] 2015-12-17 14:04
sorry, I've never used 1.0 because of other reasons

**Comment by jamadden** [comment] 2015-12-17 14:10
If it worked it 1.0 but does not in 1.1, then it's a regression and thus potentially higher priority to fix. If it didn't, then it's a new feature and, because we're in RC mode, subject to a higher bar (generally, must be less invasive). A less invasive option would be adding `import os.path` to `gevent.__init__.py:__dependencies_for_freezing()`. Does that solve your problem?

**Comment by mprosperi** [comment] 2015-12-17 14:51
doesn't work (tried also import os.path as path)

**Comment by jamadden** [comment] 2015-12-18 17:40
I had a very long post with lots of example output, but I lost it accidentally. I don't feel like creating it all again, so I'll summarize. Please excuse the brevity.

It seems like the problems with py2exe are much deeper than this. 

I was unable to get py2exe 0.6.9 to produce a working executable under Python 2.7; if I deal with the `os.path` issue, the next issue has to do with `builtins` (with or without `bundle_files=1`). It seems like anything that shadows a stdlib module causes trouble.

I was also unable to get py2exe 0.9.2.2 to produce a working executable with Python 3.4. Without bundle_files, I get 
```
>dist\concurrent_download.exe
ImportError: No module named 'collections.abc'
X:\GithubSources\gevent-main\examples\dist\library.zip\gevent\corecext.py:6: RuntimeWarning: Cython module failed to register with collections.abc module
Traceback (most recent call last):
  File "concurrent_download.py", line 10, in <module>
    monkey.patch_all()
  File "C:\Python34\lib\site-packages\gevent\monkey.py", line 503, in patch_all
    patch_ssl()
  File "C:\Python34\lib\site-packages\gevent\monkey.py", line 391, in patch_ssl
    patch_module('ssl')
  File "C:\Python34\lib\site-packages\gevent\monkey.py", line 155, in patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
ImportError: No module named 'gevent.ssl'
```

and with bundle_files, I get 
```
s>dist\concurrent_download.exe
ImportError: No module named 'collections.abc'
X:\GithubSources\gevent-main\examples\dist\library.zip\zipextimporter.py:109: RuntimeWarning: Cython module failed to register with collections.abc module
Traceback (most recent call last):
  File "concurrent_download.py", line 10, in <module>
    monkey.patch_all()
  File "C:\Python34\lib\site-packages\gevent\monkey.py", line 493, in patch_all
    patch_thread(Event=Event)
  File "C:\Python34\lib\site-packages\gevent\monkey.py", line 293, in patch_thread
    patch_module('thread')
  File "C:\Python34\lib\site-packages\gevent\monkey.py", line 155, in patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
    return zipimport.zipimporter.load_module(self, fullname)
  File "C:\Python34\lib\site-packages\gevent\thread.py", line 35, in <module>
    from gevent.lock import BoundedSemaphore
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\zipextimporter.py", line 86, in load_module
    return zipimport.zipimporter.load_module(self, fullname)
  File "C:\Python34\lib\site-packages\gevent\lock.py", line 5, in <module>
    from gevent._semaphore import Semaphore, BoundedSemaphore
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\zipextimporter.py", line 109, in load_module
    self.get_data)
  File "gevent\_semaphore.py", line 1, in init gevent._semaphore (gevent/gevent._semaphore.c:5560)
SystemError: Parent module '' not loaded, cannot perform relative import
```

It seems like there are some fundamental issues to be resolved, too many for an RC cycle.

However, we do now have CI running on Windows with AppVeyor, so it should be possible to add automated tests to ensure that once it's working it stays working. I would happily review a PR for the next major milestone that fixes py2exe for (some subset of) the supported Python versions if it includes such CI integration. I have no motivation to do that work myself though.

**Comment by mprosperi** [comment] 2015-12-21 08:47
ok, thank you for your time

**Comment by Ivoz** [comment] 2016-02-03 11:32
The problem is usually py2exe trying to detect modules and libraries used, instead of just letting the user specify them. Works without configuration for simple things, but In the end they fail at some point.

**Comment by jamadden** [comment] 2016-10-26 21:05
Closing in triage for 1.2a1 and because there have been no updates since February. This seems to come down to limitations in a particular external tool that may have workarounds (configuration).

**Closed by jamadden** 2016-10-26 21:05 UTC
Labels: enhancement
