### ISSUE TITLE
SSL_v3 removed in python 2.7.8-4

### ISSUE THREAD

**Issue by laurentL** [gevent/gevent#545] opened 2015-03-21 17:07 UTC
hi,
impossible to use gevent in debian jessie:

Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/knockdaemonMaster/workspace/knockdaemon_test/TestAllSqlStuff.py", line 53, in setUp
    SolBase.voodoo_init()
  File "/var/lib/jenkins/jobs/knockdaemonMaster/workspace/.env/local/lib/python2.7/site-packages/pythonsol/SolBase.py", line 313, in voodoo_init
    monkey.patch_all(aggressive=aggressive)
  File "/var/lib/jenkins/jobs/knockdaemonMaster/workspace/.env/local/lib/python2.7/site-packages/gevent/monkey.py", line 190, in patch_all
    patch_ssl()
  File "/var/lib/jenkins/jobs/knockdaemonMaster/workspace/.env/local/lib/python2.7/site-packages/gevent/monkey.py", line 146, in patch_ssl
    patch_module('ssl')
  File "/var/lib/jenkins/jobs/knockdaemonMaster/workspace/.env/local/lib/python2.7/site-packages/gevent/monkey.py", line 62, in patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "/var/lib/jenkins/jobs/knockdaemonMaster/workspace/.env/local/lib/python2.7/site-packages/gevent/ssl.py", line 386, in <module>
    def get_server_certificate(addr, ssl_version=PROTOCOL_SSLv3, ca_certs=None):
NameError: name 'PROTOCOL_SSLv3' is not defined

**Comment by krak3n** [comment] 2015-03-22 12:52
@laurentL see #513

**Comment by thedrow** [comment] 2015-06-15 22:48
@laurentL Yup. This issue should be closed as it's a duplicate of the already resolved #513.

**Comment by jamadden** [comment] 2015-06-24 14:51
Closing as duplicate of #513.

**Closed by jamadden** 2015-06-24 14:51 UTC
Labels: duplicate
