### ISSUE TITLE
monkey.patch_all() breakes hmac.new().

### ISSUE THREAD

**Issue by easyrider666** [gevent/gevent#806] opened 2016-05-17 10:03 UTC
On an ARMv71 device the monkey.patch_all() somehow breaks the python builtin function hmac. Occasionally hmac returns wrong hash of a string. 

I have described the problem at stackoverflow: http://stackoverflow.com/questions/37209712/python3-hmac-returns-wrong-output-arm71-32bit?noredirect=1

And finally it seems like I found a solution to the problem.

If I disable ssl on the monkey patch the problem with hmac disappears. 
from gevent import monkey
monkey.patch_all(ssl=False)

Why does this happen?

**Comment by jamadden** [comment] 2016-05-17 11:59
Using the script you referenced, I cannot reproduce the problem you report using these versions on a raspberry pi:
```
$ uname -o -r -m
4.1.20-v7+ armv7l GNU/Linux
$ cat /etc/debian_version
8.0
$ python --version
Python 3.4.2
$ python -c 'import gevent; print(gevent.__version__)'
1.1.1
$ python -c 'import greenlet; print(greenlet.__version__)'
0.4.9
```

What versions are you using?

It doesn't make much sense that gevent could cause this. `hmac` uses `hashlib` which (almost always) uses the C extension module `_hashlib` which (almost always) uses OpenSSL C functions to implement SHA1, which *shouldn't* call the Python API. Indeed, when gevent patches the `ssl` module, it only changes the implementation of four things: `SSLSocket`, `SSLContext`, `wrap_socket` and `get_server_certificate`, none of which have anything to do with an OpenSSL hash.

You state that you also reproduced the problem with `eventlet`, is that still the case? The only thing that eventlet and gevent have in common is the underlying greenlet library. I can imagine that *if* some of the OpenSSL C functions are not re-entrant, and *if* they called something that allowed a greenlet switch to occur, and *if* that new greenlet also called the non-re-entrant function, state could be corrupted in a manner that leads to this kind of problem. That may be why you're trying to use multiple threads/greenlets? Could you not reproduce this in a single thread/greenlet?

But again, I can't reproduce this.

**Comment by jamadden** [comment] 2016-05-17 12:13
I also disabled hashlib's use of OpenSSL so that it falls back to the `_sha1` module builtin to python and I still cannot reproduce a problem.

**Comment by easyrider666** [comment] 2016-05-19 04:44
Hi! Thanks for the reply.

* uname -o -r -m
3.12.30-AM335x-PD15.1.0 armv7l GNU/Linux
* cat /etc/debian_version
cat: can't open '/etc/debian_version': No such file or directory
* python3 --version     (we are running python3)
Python 3.4.3
* file `which python3.4`
/usr/bin/python3.4: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dyna                       mically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=47076a998                       2ea4340a9ea3d6a7e64904c22a90853, stripped
*python3 -c 'import gevent; print(gevent.__version__)'
1.1.1
* python3 -c 'import greenlet; print(greenlet.__version__)'
0.4.9


opkg list_installed:
python3-alembic - 0.8.6-r0
python3-argparse - 1.4.0-r4
python3-audio - 3.4.3-r0.0
python3-babel - 2.2.0-r0
python3-blinker - 1.4-r0
python3-codecs - 3.4.3-r0.0
python3-compile - 3.4.3-r0.0
python3-compression - 3.4.3-r0.0
python3-core - 3.4.3-r0.0
python3-crypt - 3.4.3-r0.0
python3-ctypes - 3.4.3-r0.0
python3-datetime - 3.4.3-r0.0
python3-difflib - 3.4.3-r0.0
python3-distutils - 3.4.3-r0.0
python3-editor - 0.4-r0
python3-elementtree - 3.4.3-r0.0
python3-email - 3.4.3-r0.0
python3-engineio - 0.9.0-r0
python3-eventlet - 0.18.4-r0
python3-flask - 0.10.1-r0
python3-flask-babel - 0.9-r0
python3-flask-login - 0.3.1-r0
python3-flask-mail - 0.9.1-r0
python3-flask-migrate - 1.6.0-r0
python3-flask-principal - 0.4.0-r0
python3-flask-script - 2.0.5-r0
python3-flask-socketio - 1.0-r0
python3-flask-sqlalchemy - 2.0-r0
python3-flask-wtf - 0.12-r0
python3-fysom - 2.1.2-r0
python3-gevent - 1.1.1-r0
python3-greenlet - 0.4.9-r0
python3-html - 3.4.3-r0.0
python3-image - 3.4.3-r0.0
python3-importlib - 3.4.3-r0.0
python3-io - 3.4.3-r0.0
python3-itsdangerous - 0.24-r0
python3-jinja2 - 2.8-r0
python3-json - 3.4.3-r0.0
python3-lang - 3.4.3-r0.0
python3-logging - 3.4.3-r0.0
python3-mako - 1.0.4-r0
python3-markupsafe - 0.23-r0
python3-math - 3.4.3-r0.0
python3-mime - 3.4.3-r0.0
python3-misc - 3.4.3-r0.0
python3-multiprocessing - 3.4.3-r0.0
python3-netclient - 3.4.3-r0.0
python3-netserver - 3.4.3-r0.0
python3-numbers - 3.4.3-r0.0
python3-paho-mqtt - 1.1-r0
python3-passlib - 1.6.5-r0
python3-pickle - 3.4.3-r0.0
python3-pip - 7.1.0-r0
python3-pkgutil - 3.4.3-r0.0
python3-pprint - 3.4.3-r0.0
python3-pyserial - 2.7-r0
python3-pytz - 2016.3-r0
python3-re - 3.4.3-r0.0
python3-readline - 3.4.3-r0.0
python3-reprlib - 3.4.3-r0.0
python3-resource - 3.4.3-r0.0
python3-rrdtool - 0.1.1-r0
python3-setuptools - 18.7.1-r0
python3-shell - 3.4.3-r0.0
python3-six - 1.10.0-r0
python3-socketio - 1.2-r0
python3-speaklater - 1.3-r0
python3-sphinx - 1.3.1-r0
python3-sqlalchemy - 1.0.12-r0
python3-sqlite3 - 3.4.3-r0.0
python3-stringold - 3.4.3-r0.0
python3-subprocess - 3.4.3-r0.0
python3-textutils - 3.4.3-r0.0
python3-threading - 3.4.3-r0.0
python3-unixadmin - 3.4.3-r0.0
python3-werkzeug - 0.11.9-r0
python3-wtforms - 2.1-r0
python3-xml - 3.4.3-r0.0
python3-xmlrpc - 3.4.3-r0.0
python3-zmq - 14.7.0-r0


About Eventlet. Yes, if I use eventlet, and monkey patch the application. Same problem occur.

**Comment by easyrider666** [comment] 2016-05-19 04:46
You say that you disable OpenSSL? Does that mean you run the application in pure python? Can you please tell me how you do that?

**Comment by jamadden** [comment] 2016-05-19 12:06
> You say that you disable OpenSSL? Does that mean you run the application in pure python? Can you please tell me how you do that?

For the purpose of this test, that meant that I edited `hashlib.py` and raised an `ImportError` at the right spot so that `__get_builtin_constructor` is used instead of `_get_openssl_constructor`. These are still C builtins, they just aren't OpenSSL functions. 

I think you can build cpython entirely without OpenSSL if you choose.

> About Eventlet. Yes, if I use eventlet, and monkey patch the application. Same problem occur.

Ok, that strongly suggests that this has nothing to do with gevent. The only shared code between gevent and eventlet is the greenlet library, so I would do further debugging at that level. Probably the first thing I would do would be to rebuild greenlet without any compiler optimizations and test that; I vaguely recall something about bad compiler optimizations and greenlets. I might also try tracing the greenlets.

I'm sorry I can't be more helpful but I can't reproduce this on my ARM box, so it's something system-specific.

**Comment by jamadden** [comment] 2016-05-27 11:48
Any updates?

**Comment by easyrider666** [comment] 2016-05-27 12:41
Sorry, been busy with work. Well. We still have some problems with gevent, but using (ssl=False) makes it work. Do not know what is wrong with it.

**Comment by jamadden** [comment] 2016-05-27 13:12
I'm going to close this, then, since I couldn't reproduce it, there is a workaround and it's not actively being investigated. Please feel free to reopen or create a new issue if you want to look at this again.

**Closed by jamadden** 2016-05-27 13:12 UTC
Labels: python3, question
