### ISSUE TITLE
RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by cschj** [gevent/gevent#1680] opened 2020-09-25 09:13 UTC
* gevent version: 20.6.2
* Python version: 3.7.8
* Operating System: Linux version 4.14.105-19-0012 (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16)

### Description:
The automatically installed dependent libraries are as follows：
zope.event==4.5.0  
greenlet==0.4.17
zope.interface==5.1.0

Trying to boot a gunicorn worker with --worker-class=gevent and it logs this and then infinite reboot:

2020-09-25T08:54:14.6100283Z /usr/local/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
2020-09-25T08:54:14.610067892Z   return f(*args, **kwds)

**Comment by jamadden** [comment] 2020-09-25 10:27
Duplicate of #1678. 

If you use Python 3.7 or above, you must use greenlet 0.4.17 with gevent 20.9.0; do not update greenlet independently of gevent. Or use greenlet 0.4.16 with gevent 20.6.x.

**Closed by jamadden** 2020-09-25 10:27 UTC
