### ISSUE TITLE
Publish wheel for M1 Mac (arm64)

### ISSUE THREAD

**Issue by tyates-indeed** [gevent/gevent#1885] opened 2022-05-10 15:32 UTC
* gevent version: `21.12.0`
* Python version: `3.9.12`
* Operating System: `MacBook Air (M1, 2020) Darwin Kernel Version 21.4.0: arm64`

### Description:

Installing the latest version of `gevent` on an M1 Mac requires building from source:
```
Building wheels for collected packages: gevent
  Building wheel for gevent (PEP 517) ... done
  Created wheel for gevent: filename=gevent-21.12.0-cp39-cp39-macosx_12_0_arm64.whl size=1732438 sha256=717895d5c98c05665286ab0284629d9f1642f947b710c1ad1b3e3115d589f470
```

This takes a long time which slows down project setup. Publishing a wheel for arm64 would greatly speed this up.

### What I've run:

`pip install gevent`

**Comment by NitzanShifrin** [comment] 2022-06-15 09:30
Any updates?

**Comment by chefren** [comment] 2022-09-08 02:36
This note is still [here](http://www.gevent.org/install.html)

```


Tip

Beginning with gevent 20.12.0, 64-bit ARM binaries are distributed on PyPI for aarch64 manylinux2014 compatible systems. Installing these needs a very recent version of pip. These wheels do not contain the c-ares resolver, are not tested, and are built with very low levels of optimizations. Serious production users of gevent on 64-bit ARM systems are encouraged to build their own binary wheels. 
```

So would have to build once and keep in local package management / storage to avoid rebuild, then pip install directly the package.

**Comment by jamadden** [comment] 2022-10-06 21:51
Duplicate of #1878

**Closed by jamadden** 2022-10-06 21:51 UTC
