### ISSUE TITLE
Segmentation Fault on killing job repeatedly

### ISSUE THREAD

**Issue by jonahkichwacoders** [gevent/gevent#543] opened 2015-03-19 11:04 UTC
I am getting a segmentation fault when running gevent on this reduced test case. I am using:
gevent==1.0.1
greenlet==0.4.5
Python 2.7.8
on an Arm Linux box. The test works fine on my x86_64 Linux.

```python
import gevent

def worker():
    while True:
        gevent.sleep()
job = gevent.spawn(worker)

gevent.spawn(job.kill)
gevent.spawn(job.kill)
job.join()

```

The segmentation fault occurs when job.kill completes for the first time.

I am continuing to investigate, but any insight would be gratefully received.

**Comment by jonahkichwacoders** [comment] 2015-03-19 16:26
I have worked around this problem by turning off optimizations in greenlet and gevent.

The segfault is happening on callbacks.c:173 in function gevent_call:
The line is:
    Py_DECREF(callback);
at this point callback == 0 and prior to the call to PyObject_Call on line 161 the local variable callback was != 0.

**Comment by RudiSchloesser** [comment] 2015-04-30 20:04
Hi Jonah,
looks like I'm facing the same for PPC. I'm using bitbake and build of gevent 1.0.1 with bb-file from openembedded fails (configure in libev expects --host leading to missing config.h). Setting up the environment and running configure manually solves this problem and build of gevent succeeds. But still SIGSEGV in hub.py. How to force cython to leave out -O2 in the CFLAGS for the GCC?

**Comment by jonahkichwacoders** [comment] 2015-04-30 21:20
I had difficulty figuring out how to do it "properly", so in the end I went the patch setup.py route. As I am using buildroot, I am using its patching mechanism http://buildroot.net/downloads/manual/manual.html#customize-patches 

I have two patches, one for greenlet 0.4.5:

```patch
diff --git a/setup.py b/setup.py
index 1844948..34e919a 100755
--- a/setup.py
+++ b/setup.py
@@ -11,6 +11,9 @@ if ((sys.platform == "openbsd4" and os.uname()[-1] == "i386")
     or ("SunOS" in platform.platform() and platform.machine() == "sun4v")):
     os.environ["CFLAGS"] = ("%s %s" % (os.environ.get("CFLAGS", ""), "-Os")).lstrip()
 
+# Turn off all optimizations
+os.environ["CFLAGS"] = ("%s %s" % (os.environ.get("CFLAGS", ""), "-O0")).lstrip()
+
 try:
     if not (sys.modules.get("setuptools")
             or "develop" in sys.argv

```

one for gevent 1.0.1:

```patch
diff --git a/setup.py b/setup.py
index e75b0ab..afe12de 100755
--- a/setup.py
+++ b/setup.py
@@ -179,6 +179,9 @@ if LIBEV_EMBED:
 else:
     CORE.libraries.append('ev')
 
+# Turn off all optimizations
+os.environ["CFLAGS"] = ("%s %s" % (os.environ.get("CFLAGS", ""), "-O0")).lstrip()
+
 
 if CARES_EMBED:
     ARES.sources += expand('c-ares/*.c')
```

**Comment by RudiSchloesser** [comment] 2015-05-01 17:26
Hi Jonah,
thanks, fixed this issue. Now I'm fighting with missing symbol "clock_gettime". (-lrt missing in LDFLAGS).

**Comment by jamadden** [comment] 2015-07-02 21:52
The code in callbacks.c looks correct to me. While it would be possible to change that `Py_DECREF` to `Py_XDECREF` to be `NULL` safe, if the problem is faulty compiler optimizations I'm not sure that would actually solve the problem or just move it around.

In a normal `python ./setup.py install` invocation, compiling C extensions will append the current CFLAGS environment variable to the value provided by `sysconfig.get_config_var('OPT')` (this is in `distutils.sysconfig.customize_compiler`), so if you want to disable optimizations you can do `CFLAGS=-O0 python ./setup.py install`. I don't know anything about buildroot, but perhaps it has a less invasive way to specify environment variables than patching source files.

It doesn't look like there's anything for gevent to do here so I'm closing the issue as part of triage for the 1.1 release. Please feel free to comment more or reopen if you feel otherwise.

**Closed by jamadden** 2015-07-02 21:52 UTC
