### ISSUE TITLE
test__subprocess_interrupted.py sometimes fails with AssertionError

### ISSUE THREAD

**Issue by denik** [gevent/gevent#196] opened 2012-11-10 15:35 UTC
For example, https://travis-ci.org/SiteSupport/gevent/jobs/3141051/#L4645 :

```
| GEVENT_FILE=thread GEVENT_RESOLVER=thread /usr/bin/python2.6 -u test__subprocess_interrupted.py
Traceback (most recent call last):
File "test__subprocess_interrupted.py", line 17, in <module>
assert err.strip() == 'bye', repr(err)
AssertionError: 'bye\nUnhandled exception in thread started by \nError in sys.excepthook:\n\nOriginal exception was:\n'
! GEVENT_FILE=thread GEVENT_RESOLVER=thread /usr/bin/python2.6 -u test__subprocess_interrupted.py [code 1] [took 0.6s]
```

Seems to be timing-related, might be possible to reproduce by looping this test over.

**Comment by jamadden** [comment] 2016-10-27 13:04
This test is currently marked as FLAKY in known_failures.py, but I don't remember the last time I actually saw it fail. I'm not able to reproduce a crash running in a loop locally.

That said, I'm going to leave it marked as FLAKY, but, in the interests of triage for 1.2, I'm going to close this issue. 

A good cleanup task would be to go back through all the entries marked FLAKY and re-evaluate them.

**Closed by jamadden** 2016-10-27 13:04 UTC
