### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by singpenguin** [gevent/gevent#402] opened 2014-03-12 03:14 UTC
If you do not set headers, gevent default will add Transfer-Encoding: chunked, but it is prone Broken pipe error, 
"pywsgi.py, line 490, in process_result, self.socket.sendall ('0\r\n\r\n') "
If you set the Content-Length, this error does not occur

**Comment by jamadden** [comment] 2015-07-09 14:21
Can you provide a minimal example to reproduce the problem?

**Comment by jamadden** [comment] 2016-03-29 22:39
Closing since there have been no updates in two years. Please feel free to reopen if there is more information.

**Closed by jamadden** 2016-03-29 22:39 UTC
Labels: question
