### ISSUE TITLE
Read blocks for ever after select call on gevents subprocess.Popen pipes

### ISSUE THREAD

**Issue by bdubey** [gevent/gevent#1554] opened 2020-04-07 17:34 UTC
* gevent version: 1.2.2
* Python version: 2.7.5
* Operating System: centos x86
### Description:
Read call blocks for forever on the gevent's subprocess. Popen pipes after a select call . Interestingly a sleep before the select call solves the problem.
Also this used to work for gevent-1.0.1

### What I've run:

```python
from gevent import monkey
monkey.patch_all()

import subprocess
import select
import shlex
import time

cmd = "curl 'http://127.0.0.1:2020/h/gflags'"
cmd = shlex.split(cmd)
proc = subprocess.Popen(cmd, close_fds=True, shell=shell,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)

poll_set = set([proc.stdout, proc.stderr])
#time.sleep(5)         ######## A  sleep here solves the problem
rd, _, err = select.select(list(poll_set), [], list(poll_set))
for pipe_obj in rd:
  data = read_obj.read() ############ This blocks for ever
```

**Comment by jamadden** [comment] 2020-04-07 17:45
Can you reproduce this with something besides a custom webserver on localhost, e.g., using standard unix utilities? I obviously don't have that webserver installed so can't reproduce it that way. 

Can you reproduce this with the current gevent version (1.5)? 1.2.2 is very outdated and unsupported.

**Comment by bdubey** [comment] 2020-04-07 17:55
@jamadden Sorry we are on gevent-1.0.1 and python 2.7.5. In the release notes I read, 1.2.2 is the latest supported version for python-2.7.8 and below. As much I want, I cant go beyond gevent-1.2.2. Although I did compare the select implementation hasn't change since then in 1.4
One observation from the **gevent.select.select** implementation is a sleep before select call  always results in fdlist being nonempty from the call to 
```python
       sel_results = _original_select(rlist, wlist, xlist, 0)
```

So it never calls gevents cooperative implementation. Billow is the source from gevent

```python
def select(rlist, wlist, xlist, timeout=None): # pylint:disable=unused-argument
    if timeout is not None and timeout < 0:
        raise ValueError("timeout must be non-negative")
    sel_results = ((), (), ())
    try:
        sel_results = _original_select(rlist, wlist, xlist, 0)
    except error as e:
        enumber = getattr(e, 'errno', None) or e.args[0]
        if enumber != EINTR:
            # Ignore interrupted syscalls
            raise
    if sel_results[0] or sel_results[1] or sel_results[2]
        _g_sleep()
        return sel_results   ############## A sleep ensures we return from here and all good.

    result = SelectResult() ##################### If we are here we will block.
    return result.select(rlist, wlist, timeout)
```
I do not think the webserver matters here. Please let me know why you suspect so?

**Comment by jamadden** [comment] 2020-04-07 18:13
> In the release notes I read, 1.2.2 is the latest supported version for python-2.7.8 and below.

"Supported" meaning "has an SSL module that works with Python's SSL module" (which of course is broken). If you don't need SSL you can probably make a newer version work. It'd be totally unsupported, but no worse than gevent 1.2 is at this point.

> I do not think the webserver matters here. Please let me know why you suspect so?

I need a way to reproduce fairly exactly what you're seeing. I can't do that if you're using external systems I don't have access to. That's part of the "self contained" in [Short, Self Contained, Correct Example](http://sscce.org). In particular, I don't know what sort of timing and output characteristics this has: is it a firehose of data, or a trickle, does it disconnect in the middle, etc. All of those things can matter (have mattered in past examples). 

I will note that it's pretty odd to attempt to `select` on a subprocess pipe in such a linear flow; most people simply read the results using one of the provided methods, e.g., `communicate` or one of the many convenience methods. They spawn a separate greenlet if they don't want to yield the current greenlet while doing so (which, of course, `select` also does). Because of how awkward this example is, I assume it's cut down from some much larger system.

**Comment by bdubey** [comment] 2020-04-07 18:29
@jamadden I will attempt to repro this without the web server involved. I can't comment if SSL will be needed. I tried 1.4 but it required a later setuptools. The private cloud environment I have at my disposal is pretty rigid to allow any upgrades. I will definitely consider this suggestion though.

`communicate ` does not have a timeout option for python-2.7.  The code I shared is snipped. We actually attempt to read/poll on the pipe with a timeout. It is an old legacy code in the infrastructure. This code has to be supported without gevents as well. Monkey patching is optional. Please suggest any other way of doing it. We are with an archaic environment with little that I can do to update things. One of the reasons that I am attempting to update gevent is because we have observed differences with or without gevent and we operate both with and without gevent.

**Comment by jamadden** [comment] 2020-04-07 18:43
> `communicate` does not have a timeout option for python-2.7

It does in gevent, dating back to 1.1. One could either dynamically detect that subprocess is using gevent or supports that argument through any number of techniques, or simply import and use gevent.subprocess directly (it works without monkey-patching, though exactly how well depends on the rest of the system).

**Comment by bdubey** [comment] 2020-04-08 15:14
Thanks @jamadden 
I wrote below code to have my own version with timeout using `communicate` and `threading.Timer`. It seems to work standalone need to test widely.  
```python

def timed_command(cmd, timeout_secs=-1, env=None, close_fds=True, shell=False):
  proc = subprocess.Popen(cmd, close_fds=True, shell=shell,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  timed_out =  [False]
  # call back if timer exits
  def kill_on_timeout(proc, timed_out):
    proc.kill()
    timed_out[0] = True
  timer = Timer(timeout_secs, kill_on_timeout, args=(proc, timed_out))
  
  try:
   timer.start()
   stdout, stderr = proc.communicate()
   exit_code = proc.wait()
   if timed_out[0]:
     exit_code = -1
     print("Timed out executing %s" % cmd)
   return exit_code, stdout, stderr
  finally:
   timer.cancel()
```

**Comment by jaspal-dhillon** [comment] 2020-04-11 03:04
@jamadden I could reproduce this on a CentOS 7.6.1810 VM and with gevent 1.4.0 as well as 1.5.0 , by sending around 200K of data to the curl. 

Here's the test server (nothing fancy at all):
```
➜ cat test_server.py
import socket

data = "a" * 191530

def listen():
    connection = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    connection.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    connection.bind(('0.0.0.0', 5555))
    connection.listen(1)
    while True:
        current_connection, address = connection.accept()
        current_connection.send(data)
        current_connection.shutdown(1)
        current_connection.close()


if __name__ == "__main__":
    try:
        listen()
    except KeyboardInterrupt:
        pass
```

The test client is same as @bdubey's in the description (after fixing import and couple of syntax errors), which gets stuck at the read() and the traceback hints at greenlet not being switched in:

```
    data = read_obj.read()
  File "/root/gevent/src/gevent/_fileobjectposix.py", line 164, in readall
    data = self.__read(DEFAULT_BUFFER_SIZE)
  File "/root/gevent/src/gevent/_fileobjectposix.py", line 158, in __read
    wait_on_watcher(self._read_watcher, None, None, self.hub)
  File "src/gevent/_hub_primitives.py", line 326, in gevent.__hub_primitives.wait_on_watcher
  File "src/gevent/_hub_primitives.py", line 350, in gevent.__hub_primitives.wait_on_watcher
  File "src/gevent/_hub_primitives.py", line 304, in gevent.__hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent.__hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 151, in gevent.__waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
```

Versions:
```
➜  ~ python --version
Python 2.7.5
➜  ~ python -c "import gevent;print(gevent.version_info)"
version_info(major=1, minor=5, micro=0, releaselevel='dev', serial=0)
➜  ~ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)

And if it helps:
➜  ~ python -c "import gevent;print(gevent.config.loop)"
<type 'gevent.libev.corecext.loop'>
```

**Comment by jamadden** [comment] 2020-04-11 10:53
> by sending around 200K of data to the curl.

> Here's the test server (nothing fancy at all):

The test server isn't an HTTP server. I would expect curl to exit almost immediately when it tries to connect and finds that it isn't speaking HTTP, and it appears to do so:
```console
$ curl http://localhost:5555/h/gflags
curl: (1) Received HTTP/0.9 when not allowed

$ echo $?
1

```

Calling it from subprocess likewise exits nearly immediately:
```console
$ python /tmp/client.py
$ python /tmp/client.py
$ python /tmp/client.py
$ echo $?
0
```

Are there other changes you made? For reference, this is the version of the client I'm using:
```python
# /tmp/client.py
from gevent import monkey
monkey.patch_all()
# pylint:disable=wrong-import-position,wrong-import-order
import shlex
import subprocess
import select

cmd = "curl 'http://127.0.0.1:5555/h/gflags'"
cmd = shlex.split(cmd)
proc = subprocess.Popen(
    cmd, close_fds=True, shell=True, # JAM: Or False, either works the same
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)


poll_set = set([proc.stdout, proc.stderr])
#time.sleep(5)         ######## A  sleep here solves the problem
rd, _, err = select.select(list(poll_set), [], list(poll_set))
for pipe_obj in rd:
    data = pipe_obj.read() ############ This blocks for ever
```

**Comment by jaspal-dhillon** [comment] 2020-04-11 11:04
Well, since the server is hosted on 5555, need to make the adjustment in the curl command as well:
```
➜  ~ curl http://127.0.0.1:5555 > /dev/null; echo $?
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  203k    0  203k    0     0   289M      0 --:--:-- --:--:-- --:--:--  198M
0
```

The full test client:
```
➜  cat test_client.py
from gevent import monkey
monkey.patch_all()
import subprocess
import select

import cStringIO
import shlex
import time

cmd = "curl 'http://127.0.0.1:5555'"
cmd = shlex.split(cmd)
proc = subprocess.Popen(cmd, close_fds=True, shell=False,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)

stdout = cStringIO.StringIO()
stderr = cStringIO.StringIO()
poll_set = set([proc.stdout, proc.stderr])
#time.sleep(5)         ######## A  sleep here solves the problem
rd, _, err = select.select(list(poll_set), [], list(poll_set))
for pipe_obj in rd:
  data = pipe_obj.read() ############ This blocks for ever
```

**Comment by jaspal-dhillon** [comment] 2020-04-11 11:08
Could also repro with wget.
```
➜  ~ curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets

➜  ~ wget --version
GNU Wget 1.14 built on linux-gnu.

+digest +https +ipv6 +iri +large-file +nls +ntlm +opie +ssl/openssl

Wgetrc:
    /etc/wgetrc (system)
Locale: /usr/share/locale
Compile: gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc"
    -DLOCALEDIR="/usr/share/locale" -I. -I../lib -I../lib -O2 -g -pipe
    -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong
    --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic
Link: gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions
    -fstack-protector-strong --param=ssp-buffer-size=4
    -grecord-gcc-switches -m64 -mtune=generic -lssl -lcrypto
    /usr/lib64/libssl.so /usr/lib64/libcrypto.so /usr/lib64/libz.so
    -ldl -lz -lz -lidn -luuid -lpcre ftp-opie.o openssl.o http-ntlm.o
    ../lib/libgnu.a

Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.

➜  ~ wget -v http://127.0.0.1:5555 -O - > /dev/null; echo $?
--2020-04-11 02:11:51--  http://127.0.0.1:5555/
Connecting to 127.0.0.1:5555... connected.
HTTP request sent, awaiting response... 200 No headers, assuming HTTP/0.9
Length: unspecified
Saving to: 'STDOUT'

    [ <=>                                                                         ] 191,530     --.-K/s   in 0s

2020-04-11 02:11:51 (1.22 GB/s) - written to stdout [191530]

0
```

**Comment by jamadden** [comment] 2020-04-11 11:10
> Well, since the server is hosted on 5555, need to make the adjustment in the curl command as well:

Yes, as you can see from my examples I made that adjustment and changed the port. (The path doesn't matter because the server never examines it.)

I am using a newer version of curl, perhaps it has additional checks.
```console
$ curl --version
curl 7.69.1 (x86_64-apple-darwin19.3.0) libcurl/7.69.1 OpenSSL/1.1.1f zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0)
Release-Date: 2020-03-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTPS-proxy IDN IPv6 Largefile libz NTLM NTLM_WB PSL SSL TLS-SRP UnixSockets
```

**Comment by jamadden** [comment] 2020-04-11 11:49
If I switch to `wget` I can see this "hang" behaviour. Importantly, though, this same behavour happens *without using gevent at all* in both Python 2.7.17 and 3.8 (under gevent master, which is the same as 1.5 right now).

I *think* that's because wget is waiting for some sort of termination signal unique to HTTP 0.9. If I watch the server I can see it getting and responding to new requests from a single spawned `wget`.

Switching to the simple `nc` (netcat) command (`nc localhost 5555`) which is just a socket client and knows nothing about protocols, the hang goes away under all combos.

**Comment by jamadden** [comment] 2020-04-11 12:22
Newer versions of curl need `—http0.9` to be able to accept that old protocol. Adding that, curl behaves the same as wget: it hangs using just the standard library.

If I make the server a real HTTP server (using wsgiref) I continue to get the hang using just the standard library, or with gevent.

However, altering the client to loop, instead of trying to read everything all in one call, solves the problem under both the stdlib and gevent.

Having the server send smaller amounts of data also solves the problem.

Now we have all the data points to put this together and see that the bug is in the client code.

What's happening is that curl writes data to both stdout *and* stderr (unlike `nc`, which only writes to one) when it detects that stdout is a pipe. Pipes have limited buffer sizes inside the kernel, and once they fill up, the writer (curl) is blocked. `select.select` makes no guarantee about the order in which descriptors are returned when ready (indeed, neither does iterating sets). So the `for pipe_obj in rd:` could either read from curl's stdout or curl's stderr first; there's no way to know. If it happens to read from stderr first, the buffer for stdout will fill up and curl will be frozen. The client code is essentially running into the same warning given for [`popen.wait()`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait):

> This will deadlock when using `stdout=PIPE` or `stderr=PIPE` and the child process generates enough output to a pipe such that it blocks waiting for the OS pipe buffer to accept more data. Use Popen.communicate() when using pipes to avoid that.

Changing the client to use `stdout=subprocess.PIPE, stderr=subprocess.STDOUT` fixes the problem by having only a single pipe that needs to be read from. Likewise, making the client manually just read from `stdout` also solves the problem (the amount of data curl writes to `stderr` is small, but it never stops writing until it stops writing to `stdout`). And also, adding `-s` (silent) to curl's command causes it to not write to stderr and fixes the problem.

Inserting a `time.sleep()` might change the timing enough that `stdout` is more commonly returned as the first element from `select.select`. I don't know, I couldn't duplicate that reliably. Uncommenting the call to `time.sleep` didn't solve the hangs for me.

**Comment by bdubey** [comment] 2020-04-13 03:46
@jamadden Your analysis do seem to make sense. But I don't see this issue without gevent on `python 2.7.5` also the issue is not present even on `gevent-1.0.1`.  The behaviour of curl should remain the same in either case. And as I posted earlier for the implementation of the gevent `select.select` a sleep probably ensures that data is there before this call 
```python
sel_results = _original_select(rlist, wlist, xlist, 0)
if sel_results[0] or sel_results[1] or sel_results[2]
      _g_sleep()
      return sel_results   ############## A sleep ensures we return from here 
                                        ##############and all good.
```
If we come to gevents cooperative implementation it hangs 
```python
    result = SelectResult() ##################### If we come here we will block in read later.
    return result.select(rlist, wlist, timeout)
```

**Comment by jamadden** [comment] 2020-04-13 13:18
Thank you for the report. I do not see any defect in gevent that should be fixed.

**Closed by jamadden** 2020-04-13 13:18 UTC
Labels: Status: not gevent, Type: Question
