### ISSUE TITLE
monkey_patch LoopExit error

### ISSUE THREAD

**Issue by ethanluoyc** [gevent/gevent#686] opened 2015-11-10 14:47 UTC
Hi I am not sure why I am getting this error 

>>Traceback (most recent call last):
  File "/Users/Ethan/anaconda/envs/data/lib/python2.7/site-packages/gevent/hub.py", line 537, in switch
    switch(value)
  File "/Users/Ethan/dev/projects/nba-stats/scrape_pbp_gevent.py", line 58, in run
    logger.error('%s - Failed %s', self.name, game_id)
NameError: global name 'logger' is not defined
<built-in method switch of ThreadedScraper object at 0x106b58370> failed with NameError

as I was trying to log my greenlet action in my script. I get this error when I was hitting Ctrl-C Is this an error?
```python
logger = logging.getLogger('scraper')
logger.setLevel(logging.DEBUG)

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

fh = logging.FileHandler('scraping.log', 'w')
fh.setLevel(logging.INFO)
fh.setFormatter(formatter)

ch = logging.StreamHandler()
ch.setLevel(logging.INFO)
ch.setFormatter(formatter)

# add the handlers to the logger
logger.addHandler(fh)
logger.addHandler(ch)


class ThreadedScraper(Greenlet):
    """Threaded Downloading"""
    def __init__(self, i, queue, **kargs):
        Greenlet.__init__(self)
        self.name = 'Scraper %s ' % i
        self.queue = queue
        self.logger = kargs['logger']
    def run(self):
        while True:
            try:
                game_id = self.queue.get()
                g = {'game_id': game_id,
                    'boxscore_html': boxscore_html(game_id),
                    'pbp_html': play_by_play_html(game_id)}
                logger.info('%s - Succeeded %s', self.name, game_id)
                self.parse(g)
                self.queue.task_done()
            except Exception as e:
                logger.error('%s - Failed %s', self.name, game_id)
                # logger.exception(e)
            finally:
                if self.queue.empty():
                    break
        self.kill()

    def _run(self):
        self.run()

    def parse(self, game):
            game_id = game['game_id']
            g = get_game_from_html(game['game_id'], \
                game['boxscore_html'].text, \
                game['pbp_html'].text)
            game_name = encode_gamename(g)+'.json'
            with open(os.path.join('data', game_name), 'w') as f:
                json.dump(g, f, indent=4)

def main(game_ids):
    queue = JoinableQueue()
    for game in game_ids:
        logger.info('Will be parsing %s', game)
        queue.put(game)

    glts = []
    for i in range(MAX_NUM):
        scraper = ThreadedScraper(i, queue, logger=logger)
        glts.append(scraper)
        scraper.start()

    gevent.signal(signal.SIGQUIT, gevent.kill)
    gevent.joinall(glts)
```

**Comment by ethanluoyc** [comment] 2015-11-11 04:07
Well just ignore the previous post, I realized that maybe this is something to do with the monkey_patch

```python
import gevent
from gevent import monkey
from gevent import select

monkey.patch_all()
# monkey.patch_socket()
import time

import urllib2

start = time.time()
tic = lambda: 'at %1.1f seconds' % (time.time() - start)

def gr1():
    # Busy waits for a second, but we don't want to stick around...
    print('Started Polling: %s' % tic())
    # select.select([], [], [], 2)
    res = urllib2.urlopen('http://www.google.com')
    print('Ended Polling: %s' % tic())

def gr2():
    # Busy waits for a second, but we don't want to stick around...
    print('Started Polling: %s' % tic())
    select.select([], [], [], 2)
    # requests.get('www.google.com')
    print('Ended Polling: %s' % tic())

def gr3():
    print("Hey lets do some stuff while the greenlets poll, %s" % tic())
    gevent.sleep(1)


gevent.joinall([
    gevent.spawn(gr1),
    gevent.spawn(gr2),
    gevent.spawn(gr3),
])

```
This wil run into `gevent.hub.LoopExit: This operation would block forever`
But if I change the patch from `patch_all()` to `patch_socket()` everything seems to work as normall.

I thought since both alter the system's socket module, the result should be the same?

**Comment by ethanluoyc** [comment] 2015-11-11 04:28
it appears that this error is due to `patch_thread()`, setting `patch_all(thread=False)` seems to work

**Comment by ml31415** [comment] 2015-12-09 09:14
The script with patch_all ran fine for me several times. Is it happening just spontaneously for you or 100% reproducible?

**Comment by ethanluoyc** [comment] 2015-12-14 15:11
I have not touched on it for some time but I believe when I was running it it it 100% reproducible.

**Comment by jamadden** [comment] 2015-12-14 15:32
I also cannot reproduce any problem with the script.

**Comment by jamadden** [comment] 2016-02-03 22:34
Closing in triage. Please re-open or open a new issue if this is still a problem.

**Closed by jamadden** 2016-02-03 22:34 UTC
Labels: question
