### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by mwerezak** [gevent/gevent#1651] opened 2020-06-23 21:58 UTC
* gevent version: 20.6.2
* Python version: cPython 3.8.2 downloaded from python.org
* Operating System: Windows 10 Pro

### Description:

This exception gets thrown from somewhere in gevent.

```python traceback
Error
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Program Files\Python38\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "C:\Program Files\Python38\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "C:\Users\Gabe2\Projects\maps\mapapi\tests\test_queue.py", line 196, in test_queue_get_index_out_of_range
    self.assertFailedResponse(response, 404)
  File "C:\Users\Gabe2\Projects\maps\mapapi\tests\support.py", line 26, in __exit__
    self.stop()
  File "C:\Users\Gabe2\Projects\maps\mapapi\tests\support.py", line 35, in stop
    self.__server.stop()
  File "C:\Users\Gabe2\Projects\maps\mapapi\venv\lib\site-packages\gevent\baseserver.py", line 386, in stop
    self.close()
  File "C:\Users\Gabe2\Projects\maps\mapapi\venv\lib\site-packages\gevent\baseserver.py", line 348, in close
    self.stop_accepting()
  File "C:\Users\Gabe2\Projects\maps\mapapi\venv\lib\site-packages\gevent\baseserver.py", line 192, in stop_accepting
    self._watcher.close()
AttributeError: 'NoneType' object has no attribute 'close'

```

### What I've run:
My application only imports gevent to get WSGIServer. The exception happens when running integration tests. The test server has to run in a separate thread, as serve_forver() blocks until the server is stopped.

```python
from threading import Thread
from gevent.pywsgi import WSGIServer
from mapapi import wsgi_app

def create_server(address: Tuple[str,int], **kwargs)
    return WSGIServer(address, wsgi_app, **kwargs)

class TestServer:
    __server = None
    def __init__(self, hostname, port):
        self.thread = Thread(None, self.__run_server, 'test_server', [hostname, port], daemon=True)

    def __run_server(self, hostname, port):
        self.__server = create_server((hostname, port), log=None)
        self.__server.serve_forever()

    def start(self):
        self.thread.start()

    def stop(self):
        if self.__server is not None:
            self.__server.stop()
            self.__server.close()
            self.__server = None
```

**Comment by jamadden** [comment] 2020-06-23 22:31
It seems you may have a race condition caused by accessing the server from multiple threads. It is a single-threaded object. If two threads attempt to shut it down at the same time, you'll get this error.

Note how `stop_accepting` carefully checks if `self._watcher` is None or not before proceeding. The only way to get that error there is if two threads attempt to call that at the same time and interfere with each other. Most gevent objects assume single-threaded use like that.

https://github.com/gevent/gevent/blob/6cf30c4ec8d2f33ada8d5e7fecfeb1c475d9b5a5/src/gevent/baseserver.py#L189-L193

It's common to put the server in its own *greenlet* (**not** thread) in order to continue executing other things. 

Many of gevent's own tests don't even need to do that; so long as network IO yields to the event loop (i.e., is using `gevent.socket`), if you've called `server.start()` it will run when that happens.

**Comment by jamadden** [comment] 2020-12-17 13:33
No updates since June, closing.

**Closed by jamadden** 2020-12-17 13:33 UTC
Labels: Type: Question
