### ISSUE TITLE
python3.11 + gevent -> returned NULL without setting an exception

### ISSUE THREAD

**Issue by SmallPineApp1e** [gevent/gevent#1987] opened 2023-08-24 08:31 UTC
* gevent version: 22.10.2，installed it from PyPI
* greenlet version: 2.0.2, installed it from PyPI
* Python version: cPython 3.11.3
* Operating System: Debian Linux 10.0

### Description:

When I use Python3.11 running in Docker, it will be hit this SystemError in random time, and then the program exit abnormally, and This error cannot be occurred stably, it confused me a long time. 

```python-traceback
Traceback (most recent call last):
  File "./start.py", line 44, in <module>
  File "./base/server.py", line 144, in start
  File "src/gevent/greenlet.py", line 1065, in gevent._gevent_cgreenlet.joinall
  File "src/gevent/greenlet.py", line 1075, in gevent._gevent_cgreenlet.joinall
  File "src/gevent/_hub_primitives.py", line 250, in gevent._gevent_c_hub_primitives.wait_on_objects
  File "src/gevent/_hub_primitives.py", line 287, in gevent._gevent_c_hub_primitives.wait_on_objects
  File "src/gevent/_hub_primitives.py", line 185, in gevent._gevent_c_hub_primitives._WaitIterator.__next__
  File "src/gevent/_hub_primitives.py", line 176, in gevent._gevent_c_hub_primitives._WaitIterator.__next__
  File "src/gevent/_waiter.py", line 195, in gevent._gevent_c_waiter.MultipleWaiter.get
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
  File "src/gevent/_waiter.py", line 122, in gevent._gevent_c_waiter.Waiter.switch
SystemError: <built-in method switch of gevent._gevent_cgreenlet.Greenlet object at 0x7f05aeb12520> returned NULL without setting an exception
```

### Sample Code:

```python
import gevent

def run(self):
   print "worker is running."
   # server object is defined in my project somewhere, it has a stop flag to judge the current server status(run or 
   while not server.stop:
        # some network I/O operation using gevent.spawn
        pass

threads = []
worker_cnt = 10
for i in range(worker_cnt):
    threads.append(gevent.spawn(run))

gevent.joinall(threads)
```

### Other
Because I want to upgrade my python version from 3.7 to 3.11, and I must upgrade the greenlet and gevent version, but they can not run stably in 3.11.

hop someone can help to solve this or provide some ideas I can try, thanks! :(

**Comment by SmallPineApp1e** [comment] 2023-08-24 11:08
I found an stable reoccurred exception, When the requests library raise this exception in one coroutine, the program will be shutdown abnormally and occur the SystemError above.

- request version：`requests==2.31.0`
- urllib3 version：`urllib3==2.0.2`

Here is the stacktrace:

```python-traceback
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^
RuntimeError: super(): __class__ cell not found
```

**Comment by kkszysiu** [comment] 2023-08-25 00:04
Hey guys, seems like it started to happen for me as well after I upgraded urllib3 to `1.26.16`, after I downgraded it back to `urllib3[secure]==1.26.12` the issue is no longer happening.

**Comment by SmallPineApp1e** [comment] 2023-08-25 02:25
> Hey guys, seems like it started to happen for me as well after I upgraded urllib3 to `1.26.16`, after I downgraded it back to `urllib3[secure]==1.26.12` the issue is no longer happening.

But it sometimes core without this RuntimeError, and I can't get any useful stacttrace, I believe the above requests error is one of the reasons cause the program abnormally exit.

**Comment by kkszysiu** [comment] 2023-08-25 03:04
I do not know. Currently I on my envinronment I am running these library versions: 
```
requests==2.28.1
urllib3==1.26.12
celery==5.3.1
gevent==23.7.0
```

And a Python 3.11.1 and so far this setup works for me just fine.

**Comment by sourcematters** [comment] 2023-08-25 03:57
I started to experience this in my Docker container as well. 

```
python 3.11.2
gevent             23.7.0
greenlet           2.0.2
gunicorn           21.2.0
```

```
2023-08-24 22:56:36 [2023-08-24 22:56:35 -0500] [1] [CRITICAL] WORKER TIMEOUT (pid:144)
2023-08-24 22:56:36 Exception ignored in: <module 'threading' from '/usr/local/lib/python3.11/threading.py'>
2023-08-24 22:56:36 Traceback (most recent call last):
2023-08-24 22:56:36   File "/usr/local/lib/python3.11/site-packages/gevent/monkey.py", line 868, in _shutdown
2023-08-24 22:56:36     orig_shutdown()
2023-08-24 22:56:36   File "/usr/local/lib/python3.11/threading.py", line 1553, in _shutdown
2023-08-24 22:56:36     atexit_call()
2023-08-24 22:56:36   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit
2023-08-24 22:56:36     t.join()
2023-08-24 22:56:36   File "/usr/local/lib/python3.11/threading.py", line 1112, in join
2023-08-24 22:56:36     self._wait_for_tstate_lock()
2023-08-24 22:56:36   File "/usr/local/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock
2023-08-24 22:56:36     if lock.acquire(block, timeout):
2023-08-24 22:56:36        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-24 22:56:36   File "/usr/local/lib/python3.11/site-packages/gevent/thread.py", line 112, in acquire
2023-08-24 22:56:36     acquired = BoundedSemaphore.acquire(self, blocking, timeout)
2023-08-24 22:56:36                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-24 22:56:36   File "src/gevent/_semaphore.py", line 180, in gevent._gevent_c_semaphore.Semaphore.acquire
2023-08-24 22:56:36   File "src/gevent/_semaphore.py", line 249, in gevent._gevent_c_semaphore.Semaphore.acquire
2023-08-24 22:56:36   File "src/gevent/_abstract_linkable.py", line 521, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait
2023-08-24 22:56:36   File "src/gevent/_abstract_linkable.py", line 487, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
2023-08-24 22:56:36   File "src/gevent/_abstract_linkable.py", line 490, in gevent._gevent_c_abstract_linkable.AbstractLinkable._wait_core
2023-08-24 22:56:36   File "src/gevent/_abstract_linkable.py", line 442, in gevent._gevent_c_abstract_linkable.AbstractLinkable._AbstractLinkable__wait_to_be_notified
2023-08-24 22:56:36   File "src/gevent/_abstract_linkable.py", line 451, in gevent._gevent_c_abstract_linkable.AbstractLinkable._switch_to_hub
2023-08-24 22:56:36   File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
2023-08-24 22:56:36   File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
2023-08-24 22:56:36   File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
2023-08-24 22:56:36   File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
2023-08-24 22:56:36     sys.exit(1)
2023-08-24 22:56:36 SystemExit: 1
```

Not exactly sure when it started unfortunately. Do we need to lock gevent to a specific version for the time being?

**Comment by jamadden** [comment] 2023-08-30 21:45
This is a duplicate of #1985; please add additional comments to that issue.

**Closed by jamadden** 2023-08-30 21:45 UTC
