### ISSUE TITLE
deadlock when generating greenlets from existing greenlets

### ISSUE THREAD

**Issue by uriva** [gevent/gevent#1479] opened 2019-11-13 13:27 UTC
* gevent version: 1.4.0
* Python version: 3.7
* Operating System: linux

I'm using this decorator to wrap `f`, a function that uses `requests` (I'm also using `monkey.patch_all`):

```python

def _run_interval(func):
    gevent.spawn_later(0, func)
    gevent.spawn_later(0.5, _run_interval, func)

def batch_calls(f):
    """Turns `f`, a function that gets a `tuple` of independent requests, into a function that gets a single request."""
    queue = {}
    queue_lock = lock.BoundedSemaphore(1)

    def make_call():
        queue_lock.acquire()
        if not queue:
            queue_lock.release()
            return
        call_params = tuple(queue.keys())
        async_results = tuple(queue.values())
        queue.clear()
        queue_lock.release()
        logging.info(
            f"cleared out queue for {f.__name__} with {len(call_params)} calls: {call_params}."
        )
        results = f(call_params)
        logging.info(
            f"returned from {f.__name__} with results for {len(call_params)} calls: {call_params}."
        )
        for async_result, result in zip(async_results, results):
            async_result.set(result)

    _run_interval(make_call)

    def wrapped(hashable_input, timeout=5):
        queue_lock.acquire()
        if hashable_input not in queue:
            queue[hashable_input] = event.AsyncResult()
        async_result = queue[hashable_input]
        queue_lock.release()
        assert (
            async_result in queue.values() or async_result.done()
        ), "Promise not in queue and not done. That should never happen."
        try:
            return async_result.get(timeout=timeout)
        except gevent.Timeout:
            if async_result in queue.values():
                logging.info(
                    f"Request [{hashable_input}] for {f.__name__} timed out, but promise in queue. Retrying."
                )
            else:
                logging.error(
                    f"Promise not in queue for [{hashable_input}] for {f.__name__}, and was not resolved (done={async_result.done()}). Retrying."
                )
            return wrapped(hashable_input, timeout)

    return wrapped
```

These things don't make sense:
1. The `logging.error` gets printed over and over again - without the log about the queue being cleared.
2. The run interval stops working at this point or the queue is both empty and not empty at the same time (multiple queue objects?)

**Comment by jamadden** [comment] 2019-11-13 13:49
How would I run this to reproduce what you're seeing? Can you provide a [short, self-contained example](http://sscce.org)?

**Comment by jamadden** [comment] 2019-11-13 13:50
Also, how did you install gevent? Do you see the problem using the current version of gevent (1.5a2)?

**Comment by uriva** [comment] 2019-11-13 13:58
Sadly this happens within a larger system, at rare occasions. I haven't managed to create a minimal example yet (didn't even manage to repro it on my local machine).

I haven't checked 1.5a2, any related changes that might help there?

**Comment by uriva** [comment] 2019-11-13 14:21
If I add some `nonlocal` statements and more logging, I now get the second log (promise in queue, retrying) but the function set to run at each interval isn't called.

Could it be that the spawned greenlets are being starved somehow?

**Comment by uriva** [comment] 2019-11-13 14:23
btw is there a difference between `spawn(f)` and `spawn_later(0, f)`?

**Comment by jamadden** [comment] 2019-11-13 15:14
> I haven't checked 1.5a2, any related changes that might help there?

Possibly. Event loop implementations have been updated, lots of changes to make spawning greenlets more efficient.

> Could it be that the spawned greenlets are being starved somehow?

Possibly. The [monitoring functionality](http://www.gevent.org/monitoring.html) might be useful, as might adjusting the [switch interval](http://www.gevent.org/api/gevent.html#switching).

> btw is there a difference between spawn(f) and spawn_later(0, f)?

Yes, a big one. The internal implementation is completely different. The first uses a loop callback while the second uses a loop timer. The callback may or may not be called without cycling the event loop subject to the switch interval and blocking; loop timers don't fire until the event loop cycles IIRC (plus, the exact details depend on the whether the libev or libuv loop implementation is used).

**Comment by uriva** [comment] 2019-11-15 00:31
With 1.5a2 I'm still seeing the "impossible" `logging.error` line, but the scheduling seems to work (I also changed it to:
```
def _run_interval(func):
    gevent.spawn(func)
    gevent.spawn_later(0.5, _run_interval, func)
```
I'm not sure which did the trick here (sorry for the mixed experiment, the iteration speed is hell).

Still I can't grok how is it that a promise is created, not in the queue and not resolved.

**Comment by uriva** [comment] 2019-11-15 02:34
Changed the code a bit and now again encountering what looks like a deadlock and `_run_interval` isn't called.

This is the new code:


```python
def _run_interval(func):
    gevent.spawn(func)
    gevent.spawn_later(0.5, _run_interval, func)


def batch_calls(f):
    """Turns `f`, a function that gets a `tuple` of independent requests, into a function that gets a single request."""
    queue = {}
    queue_lock = lock.BoundedSemaphore(1)

    def make_call():
        if not queue or queue_lock.locked():
            return
        queue_lock.acquire()
        logging.info(f"Entered `make_call` of {f.__name__} with {len(queue)} items.")
        try:
            for async_result, result in zip(queue.values(), f(tuple(queue.keys()))):
                async_result.set(result)
        except Exception as exception:
            for async_result in queue.values():
                async_result.set_exception(exception)
        queue.clear()
        queue_lock.release()

    _run_interval(make_call)

    def wrapped(hashable_input):
        queue_lock.acquire()
        if hashable_input not in queue:
            queue[hashable_input] = event.AsyncResult()
        async_result = queue[hashable_input]
        queue_lock.release()
        try:
            return async_result.get(timeout=5)
        except gevent.Timeout:
            if async_result not in queue:
                logging.error(
                    f"`async_result` for [{hashable_input}] not resolved and not in queue."
                )
            return wrapped(hashable_input)

    return wrapped
```

Could it be a bug in the semaphore implementation?

If it helps, I'm running under gunicorn, and gevent spawned functions spawn more functions of their own, and I'm using pool too.

**Comment by uriva** [comment] 2019-11-15 03:11
Is is safe to assume that gevent never does a context switch between non io standard library functions, even if you monkey patch all?

**Comment by jamadden** [comment] 2019-11-15 11:52
> Is is safe to assume that gevent never context switches between non-io standard library functions, even if you monkey patch all?

Not in general, no. To pick just one example, what if somewhere in the call tree a lock is contested? `logging` uses large locks and can be configured to use sockets, so it could switch while holding a lock, and blocking on locks also switches.

**Comment by uriva** [comment] 2019-11-17 16:24
I switched the implementation to threads and still seeing the same deadlock. Maybe I'm making too many threads/greenlets which chokes everything up. Is there a ballpark number of greenlets that makes sense? I saw in the monitor logs I have at least 6k at some point.

**Comment by uriva** [comment] 2019-11-26 10:30
Interestingly this deadlock started happening in other unrelated code, which only has pools calling pools. I'm guessing this is caused by nesting of greenlets which alongside with a limit on the amount of greenlets can cause a deadlock (not enough greenlets to return from the call stack).

Does this make any sense? Is there a hard limit on the number of active greenlets?

**Comment by uriva** [comment] 2019-11-26 10:33
when aborting this deadlock using ctrl+c the logs show this exception:

```
During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
~/airbud/venv/lib/python3.7/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    378                 # Python 2.7, use buffering of HTTP responses
--> 379                 httplib_response = conn.getresponse(buffering=True)
    380             except TypeError:

TypeError: getresponse() got an unexpected keyword argument 'buffering'
```

**Comment by jamadden** [comment] 2020-05-13 20:15
> Is there a hard limit on the number of active greenlets?

No, the number of active greenlets is limited by available memory only. Nothing is hardcoded. Though, as the number goes up, the relative percentage that can be processed during an iteration of the event loop will go down. For very large numbers, you might want to adjust the switch interval.

>  which only has pools calling pool

That seems like a likely source of the issue, since adding to pools blocks by default. The `add` and `start` methods were changed relatively recently to add non-blocking options.

There hasn't been any activity on this issue in quite a while, so I'm closing it. Feel free to re-open if there is additional information to add.

**Closed by jamadden** 2020-05-13 20:15 UTC
