### ISSUE TITLE
Issue with Greenlet 0.4.17

### ISSUE THREAD

**Issue by jkfran** [gevent/gevent#1675] opened 2020-09-22 13:02 UTC
* gevent version: 20.6.2
* Python version: Please be as specific as possible: "cPython 3.8.2"
* Operating System: Please be as specific as possible: "Ubuntu (Linux 8e4dd7170f65 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)"

### Description:
The last version of greenlet is causing segmentation fault (core dumped) with gevent.

```
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
./entrypoint: line 10:     7 Segmentation fault      (core dumped) talisker.gunicorn.gevent webapp.app:app --bind $1 --worker-class gevent --name talisker-`hostname`
```

**Comment by jamadden** [comment] 2020-09-22 13:03
Thanks for the report. This is a duplicate of https://github.com/gevent/gevent/issues/1674. For now, please install greenlet < 0.4.17 or build greenlet with `-DGREENLET_USE_CONTEXT_VARS=0`.

**Closed by jamadden** 2020-09-22 13:03 UTC
