### ISSUE TITLE
Multi-processing gotchas with PyWSGI

### ISSUE THREAD

**Issue by RichardFoo** [gevent/gevent#1179] opened 2018-04-18 00:24 UTC
* gevent version: 1.2.2

* Python version: Python 3.6.4 (default, Dec 19 2017, 14:48:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
* Python version: Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

* Operating System: CentOS Linux release 7.4.1708 (Core)
* Operating System: Mac OS 10.12.6

### Description:

On CentOS 7.4, pywsgi.WSGIServer is spawned in a sub-process when the multiprocessing module is imported (for other purposes).  (More specifically, the request-servicing threads are all started under that same sub-process - presumably, because WSGI is running there.)

This causes issues when other threads in the main process need to share memory space with the request-servicing threads (e.g., doing a send() on all connected websocket objects, which are instantiated in WSGI's process).  While there are IPC solutions for such comms, I want to avoid that here because I have no requirement for WSGI to run in a separate process.

This behavior is not seen testing locally on a laptop under Mac OS 10.12.6.  On this platform, pywsgi.WSGIServer runs in the main process.  Life is good.

### What I've run:

Poking around the gevent docs/source code, I've tried specifying spawn=None with no change in this behavior (but new errors).

No surprise here, but the behavior's no different whether I use gevent or thread to launch the thread for background(), which runs in the main process.

Here's a simplified look at the code, hopefully not leaving out any essential elements.  background() (not shown) is just a loop that wakes every 0.1 secs to do some checking and relay messages to all the WebSocket clients (like an echo server).

```python
#!/usr/bin/env python3

# 18Apr2018 - gevent multi-process test harness


import gevent
import gevent.monkey
gevent.monkey.patch_all()

from multiprocessing import Process

try:
	import thread
except ImportError:
	import _thread as thread


from flask import Flask
from flask_sockets import Sockets
import json, time, os


from gevent import pywsgi
from geventwebsocket.handler import WebSocketHandler


app = Flask(__name__)
sockets = Sockets(app)


def newProcess():
	print('Explicit process spawn   PID:', os.getpid(), ' Parent:',os.getppid())
	while True:
		time.sleep(1)


@sockets.route('/feed')
def newClient(ws):
	ws.send('Connected to the server.')
	print('New client               PID:', os.getpid(), ' Parent:',os.getppid())

	while not ws.closed:
		try:
			message = None
			message = ws.receive()
		except:
			pass
		if message is None:
			break

	print('Client socket closed     PID:', os.getpid(), ' Parent:',os.getppid())
	ws.close()



def background():
	print('Background()             PID:', os.getpid(), ' Parent:',os.getppid())

	if 0:
		print('Delaying launch of new processes, so WSGI starts first.')
		time.sleep(2)
	else:
		print('Launching sub-processes immediately, before WSGI starts.')

	p = Process(target=newProcess)
	p.start()

	p = Process(target=newProcess)
	p.start()

	while True:
		print('Background() looped      PID:', os.getpid(), ' Parent:',os.getppid())
		time.sleep(1)


if __name__ == "__main__":
	print('Main process             PID:', os.getpid(), ' Parent:',os.getppid())


	thread.start_new_thread(background,)
# 	background_task = gevent.spawn(background)

		#Delay here, so we control the sequence of when the WSGI starts
		#This delay causes WSGI to report failure to open the socket, claiming it's already in use.
		#It seems to be because two copies of this thread are running in parallel, and WSGI is actually
		#being instantiated in each process.
		#Despite receiving failures from 2 instances, you'll still be able to connect to one working instance.
		#Curiously, without this delay, we don't receive the socket errors - perhaps because timing
		#causes them to share a single socket file descriptor by forking after it's created.
	time.sleep(1)
	print('Instantiating WSGI       PID:', os.getpid(), ' Parent:',os.getppid())

	server = pywsgi.WSGIServer(('', 3333), app, handler_class=WebSocketHandler)
	server.serve_forever()
```

**Comment by Richard-Foo** [comment] 2018-04-18 04:42
Also... tried multiple kernels with CentOS, with same results:
Linux 3.10.0-327.4.4.el7.centos.plus.x86_64
Linux 3.10.0-514.16.1.el7.x86_64

And, FYI... the 'import websockets' is for websocket-client, because this app is both a websocket server and a websocket client to another server.

**Comment by jamadden** [comment] 2018-04-18 13:16
So you're saying that simply adding 'from multiprocessing import Process' causes this issue, but only on one machine? That's odd, to say the least. Can you reproduce this issue using only the standard library and gevent? If not, then it's probably something being done by one of the third-party dependencies. If so, then it's possibly an issue in your environment or with your python installation; I would suggest trying a new virtualenv, a different user account, and installing a different Python interpreter (e.g., build from source) in that order.

**Comment by Richard-Foo** [comment] 2018-04-18 21:29
Thanks for your prompt reply.  More testing is showing this to be even more peculiar - and, as one would expect, triggered by a bad practice on my part.

The issue is not the presence of multiprocessing, per se, but rather that I'm spawning other processes.  More specifically, *when* I'm spawning those processes.  Some weirdness results, and it shows up in WSGI.

The smart practice seems to be only forking from a single-threaded process.  If I follow that guidance, then the behavior in all forms should be avoided, and WSGI will run in the intended process.

### Background

It seems that spawning a process from within a multi-threaded process can be problematic.  Python docs devote one sentence to the caution, but some digging shows more references.  Generally, the precautions are because the state of global vars that get cloned is indeterminate when the parent process is multithreaded.

Threads aren't *supposed* to be cloned during a fork(), but the evidence sure looks that way - like, multiple instances of WSGI trying to open the same socket (with later instances being in the sub processes, as I initially reported); also, websocket client connections opened before a fork being serviced in each of the child processes.  (Try opening a connection, then closing it after the fork, and you'll see the close message appear from each process.)

I'll revise the script above to be more complete and show the behavior I was running into.

**Comment by jamadden** [comment] 2018-04-18 21:31
Multiple *threads* don't survive a fork(), but multiple *greenlets* do. All greenlets that were running in the current thread before the fore are still running in the child process after the fork. That may be what you were seeing.

**Comment by Richard-Foo** [comment] 2018-04-18 21:37
With further digging, it seems that the behavior I'm seeing is actually the same across platforms, with a distinction on MacOS - when a client connects on MacOS, it seems that the socket handler for the first instance (main process) of WSGI gets the call, and so the requests gets serviced in the main process' memory space.  With Linux distros, one of the later processes ends up being the one handling the connection, resulting in the servicing threads being in a sub-process.

If anyone can explain why this is happening, I'd be curious for an answer.  I can only surmise that it's an artifact of how Python is doing pseudo-threading and spawning processes, since the consensus seems to be that the OS wouldn't copy threads during a fork operation.

**Comment by Richard-Foo** [comment] 2018-04-18 21:38
Aha.  Thanks, jamadden.  That seems clearly to be what's happening here.  I presume the response threads are actually greenlets, then.

**Closed as completed** 2018-04-18 22:24 UTC

**Comment by jamadden** [comment] 2018-04-18 22:26
Python's threads *are* real OS level threads. But when you put `gevent.monkey.patch_all()` at the top of your program, you change the API so that code that is using `threading.Thread` is really creating a greenlet, not a Python thread. And as mentioned earlier, greenlets are preserved across fork, while threads are not.
