### ISSUE TITLE
OSX gevent hangs on select.select() in thread

### ISSUE THREAD

**Issue by amoffat** [gevent/gevent#526] opened 2014-12-30 18:22 UTC
This [issue](https://github.com/amoffat/sh/issues/208) was discovered by a user of my project sh.py.  When he monkey-patched his modules on OSX, `select.select()` hangs.  Works fine on ubuntu.  Here's some minimal code to reproduce the issue:

**broken**
* OSX 10.9.5
* Python 2.7.5
* gevent 1.0.1

**works**
* Ubuntu 14.10
* Python 2.7.8
* gevent 1.0.1

```python
import gevent.monkey
gevent.monkey.patch_all()

import os
import time
import threading
import select
import pty
import sys
import traceback


# this thread will just read output from our child process in our parent
# process
def t1(fd):
    while True:
        outputs, inputs, err = select.select([fd], [], [], 0.1) 
        for o in outputs:
            try:
                data = os.read(o, 1)
            except OSError:
                return
            sys.stdout.write(data)
            sys.stdout.flush()
        time.sleep(0.01)

# pipe input
stdin_fd, slave_stdin_fd = os.pipe()
# tty output
stdout_fd, slave_stdout_fd = pty.openpty()
# pipe error
stderr_fd, slave_stderr_fd = os.pipe()

pid = os.fork()

if pid == 0:
    try:
        os.close(stdin_fd)
        os.close(stdout_fd)
        os.close(stderr_fd)

        os.dup2(slave_stdin_fd, 0)
        os.dup2(slave_stdout_fd, 1)
        os.dup2(slave_stderr_fd, 2)

        # write our message
        os.write(1, "hi from the child\n")
        os.flush(1)

        time.sleep(2)
    except:
        with open("fork_exception", "w") as h:
            h.write(traceback.format_exc())
            h.write("\n")
            h.write(repr(sys.exc_info()))
            h.write("\n")
    finally:
        os._exit(255)
else:
    os.close(slave_stdin_fd)
    os.close(slave_stdout_fd)
    os.close(slave_stderr_fd)

    thread = threading.Thread(target=t1, args=(stdout_fd,))
    thread.daemon = True
    thread.start()

    pid, exit_code = os.waitpid(pid, 0)
    thread.join()
```

output on ubuntu:
```hi from the child```

output on osx, after hanging and `^C`:
```
^CKeyboardInterrupt
Traceback (most recent call last):
  File "testgevent.py", line 69, in <module>
    thread.join()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 947, in join
    self.__block.wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 339, in wait
    waiter.acquire()
  File "_semaphore.pyx", line 112, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:3004)
  File "/Users/amoffat/.virtualenvs/sh/lib/python2.7/site-packages/gevent/hub.py", line 331, in switch
    return greenlet.switch(self)
KeyboardInterrupt
```

The traceback doesn't show the `select.select()` locking I imagine because the main thread caught my KeyboardInterrupt.

**Comment by kolis** [comment] 2015-04-15 15:02
+1

**Comment by jamadden** [comment] 2015-07-02 17:30
Thank you for the great report and the minimal example! That made the investigation much easier.

I think what's happening here is a type of a race condition, possibly coupled with a difference in the way that platforms buffer their ptys. The problem is in these lines:

```python
    thread = threading.Thread(target=t1, args=(stdout_fd,))
    thread.daemon = True
    thread.start()

    pid, exit_code = os.waitpid(pid, 0)
    thread.join()
```

`os.waitpid` is a blocking function; it's not made green by gevent (for that you want a fork watcher). So the sequence of operations is this (easily confirmed with some print statements):

1. The daemon thread starts.
2. It enters its loop and calls the gevent select()
3. The gevent select cooperatively switches to some other greenlet, the main greenlet.
4. The main greenlet calls the blocking waitpid function; no other greenlet runs until the child exits.
5. The main greenlet joins the background thread which cooperatively switches to it.
6. The select call returns, saying that there's something to read on the pty. But by this time, the child process has exited and os.read returns `''`, signaling EOF and printing nothing. This loop repeats indefinitely.

If, instead of using a PTY on OS X, we use a pipe, the background thread reads all the data written by the child (prints "hi from the child"). This suggests that ptys aren't buffered by the OS but pipes are.

This looks like the classic case of calling a non-green function and disrupting the cooperative scheduling. I'm not sure what gevent could do about this specific scenario (other than monkey patch waitpid---but that's a different issue or PR).

I'm closing the issue to assist triage on the issue list as we prepare for 1.1. Please feel free to reopen and/or continue to comment if I've missed something in the discussion.

**Closed by jamadden** 2015-07-02 17:30 UTC
Labels: question
