### ISSUE TITLE
Installing on alpine via pip - possible with PEP 656?

### ISSUE THREAD

**Issue by tgross35** [gevent/gevent#1837] opened 2021-12-02 05:21 UTC
* gevent version: 21.8.0
* Python version: python 3.9.9 from Alpine in Docker
* Operating System: python:3.9-alpine: python 3.9.9 on Alpine 3.14.3

### Description:
Installing pip via `pip install gevent` still fails on Alpine for python 3.9.  Since PEP 656 (see https://github.com/pypa/packaging/pull/411, https://github.com/pypa/auditwheel/issues/305) it seems like the wheel should be workable - there is even the multilinux wheel, but it doesn't appear to work. Is adding support within gevent possible?

https://github.com/pypa/cibuildwheel has support for PEP 656.

### What I've run:
The current workaround is installing a couple of extra packages:

` RUN apk add --no-cache build-base libffi-dev `

#1824 mentions this issue but doesn't go into detail about workarounds / implementation

Also, side note: `pip install gevent==21.8.0` claims to have no version for whatever reason, only in Alpine. Running `pip install gevent>=21.1.0` or `pip install gevent` both correctly install 21.1.0

**Comment by jamadden** [comment] 2021-12-02 11:47
I'm not sure what you're asking for here, or what the "issue" is. It seems like the package compiles (installing necessary development libraries isn't a "workaround", that's just how compiling things works) and works, yes?

Otherwise, if you're just asking for a binary wheel for convenience, this seems to be a duplicate of #1824

**Comment by tgross35** [comment] 2021-12-02 19:17
@jamadden Here is better phrasing for what I'm actually asking - coming from me who doesn't know much about packaging but would like to submit a PR if it would make things easier.
- Can a wheel be created & distributed via PyPi that allows for installing without dependencies since PEP 656? (assuming yes)
- If so, what changes are necessary to this repo's project to make that happen?

I figured #1824 was more about how to add a build in general, this issue is about how to add them to the PyPi distribution. Happy to move discussion to that issue and close this one once PR requirements are defined.

**Comment by jamadden** [comment] 2021-12-03 20:07
I think both issues are the same. 

Building a binary wheel for musl based systems that can be distributed on PyPI involves adding a job to the `.github/workflows/ci.yml` that builds *and tests* gevent in a docker image. With any luck, that can just be an extra matrix entry parameterizing the `DOCKER_IMAGE` environment variable in the job that already builds manylinux wheels so that the existing build/test script (`scripts/releases/make-manylinux`) can be reused.

This is not something I have any time to do myself, but I could look at a PR.

(There's nothing stopping anyone from building their own musl wheel and installing it from a local directory or package index.)

**Closed** 2021-12-11 20:00 UTC
