### ISSUE TITLE
greenlet.error: cannot switch to a different thread with gevent(1.1b6)

### ISSUE THREAD

**Issue by zwbzzp** [gevent/gevent#689] opened 2015-11-22 19:00 UTC
When I use paramiko.SSHClient().connect(hostname,port,username,password) with python3.4:
![qq20151123-0 2x](https://cloud.githubusercontent.com/assets/8501435/11325661/43b3c898-918e-11e5-85df-25ec644846f1.png)

**Comment by jamadden** [comment] 2015-11-22 20:42
can you include the complete traceback along with all versions in use?

**Comment by zwbzzp** [comment] 2015-11-23 15:00
I can run the wssh project with python2 and gevent-1.0.2.When I use python3 to run it, I modify some bugs in gevent_websocket. 
This is the complete traceback in the debug mode and I haven’t passing parameters to paramiko.SSHClient:

After I add parameters to SSHclient, it was broken in self.spawn(fun,*args,**kwds).get():

**Comment by jamadden** [comment] 2015-11-23 16:40
It looks like you tried to include two things in your message that didn't make it through. Can you try again? Also, gevent-1.0.2 is not supported on Python 3. You need gevent >= 1.1rc1 on Python 3....but I don't think gevent_websocket supports Python 3 at all.

**Comment by zwbzzp** [comment] 2015-11-23 16:46
GeventWebsocket doesn’t support Python3, so I have modified some bugs. I will try again, thank you very much.

**Comment by jamadden** [comment] 2016-02-03 23:21
Are there any updates on this?

**Comment by jamadden** [comment] 2016-10-26 21:06
Closing in triage for 1.2a1 since there haven't been any updates since February. Feel free to re-open if there is new information.

**Closed by jamadden** 2016-10-26 21:06 UTC
Labels: python3, question

**Comment by advance512** [comment] 2017-04-16 21:41
If you see this in the context of debugging using PyCharm, try this:

Go to Settings --> Build, Execution, Deployment -> Python Debugger.
In that dialog, you'll see a "Gevent compatible" checkbox. Not sure how it got unticked in the new project.

Tick that option and enjoy!

**Comment by arcivanov** [comment] 2017-04-20 17:25
@zwbzzp FYI gevent-websocket now supports Python 3

**Comment by solitaire2015** [comment] 2017-05-13 00:52
@advance512  Thanks, it works.

**Comment by sylnsr** [comment] 2020-07-18 14:33
> If you see this in the context of debugging using PyCharm, try this:
> 
> Go to Settings --> Build, Execution, Deployment -> Python Debugger.
> In that dialog, you'll see a "Gevent compatible" checkbox. Not sure how it got unticked in the new project.
> 
> Tick that option and enjoy!

**Note**, this could give you problems when debugging newer versions of Odoo using Python > 3.5 because the "Gevent compatible" [parameter works for Python >= 2.7, Python >= 3.5](https://www.jetbrains.com/help/idea/debugger-python.html).

When debugging in Odoo 13 with Python 3.9, I found that although the app runs in debug mode, and can hit _some_ break points, [most breakpoints in classes will never work](https://stackoverflow.com/questions/62964147/pycharm-debugger-does-not-catches-breakpoints-except-when-in-method).

**Comment by advance512** [comment] 2020-07-18 19:07
Not sure I completely understand what your issue is, but I have used the
configuration above for the last 3+ years, nowadays with Python 3.8, and I
have had no issues with breakpoints.

Try to update to the latest version of PyCharm and Python and see if that
helps.

**Comment by sylnsr** [comment] 2020-07-22 00:27
> Not sure I completely understand what your issue is, but I have used the configuration above for the last 3+ years, nowadays with Python 3.8, and I have had no issues with breakpoints. Try to update to the latest version of PyCharm and Python and see if that helps.

Never the less and with all due respect sir, that is the official documentation from Jetbrains and I am sure they don't craft their documentation based on your personal experience.

**Comment by advance512** [comment] 2020-07-22 02:05
I see. Well, their documentation states:

> This parameter works for Python >= 2.7, Python >= 3.5

So, if you are using any modern version of Python (3.5 or newer) you can
expect debugging and breakpoints to work properly. If you are using Python
3.4 or older (or an EOL version of Python, like 2.x, specifically 2.6 or
older) then things indeed might will not work for you. Is this your case?

If you are running into issues with version 3.5 or newer of Python, then
you probably just need to upgrade your JetBrains tools, or have run into an
actual bug, in which case I recommend you report it.

Good luck! :)

**Comment by sylnsr** [comment] 2020-07-22 17:51
"Gevent compatible" issue is already logged as an issue 4 years ago: https://youtrack.jetbrains.com/issue/PY-11910 and apparently its still there for very few users.

**Comment by sylnsr** [comment] 2020-07-30 21:45
Regarding "Gevent compatible" setting .. . As of now, there is confirmed issue ("reproduced" status) that JetBrains confirmed. See https://youtrack.jetbrains.com/issue/PY-43676
