### ISSUE TITLE
gevent compiling hangs on cygwin python2.7

### ISSUE THREAD

**Issue by ddorian** [gevent/gevent#752] opened 2016-02-27 19:52 UTC
Hi,
After running:
`pip install --verbose gevent`

It hangs at this line:
```
 Downloading from URL https://pypi.python.org/packages/source/g/gevent/gevent-1.1rc5.tar.gz#md5=0be79bda129e4091d4fc72b8d7a54528 (from https://pypi.python.org/simple/gevent/)
    99% |████████████████████████████████| 1.9MB 576kB/s eta 0:00:01  Updating cache with response from "https://pypi.python.org/packages/source/g/gevent/gevent-1.1rc5.tar.gz"
  Caching due to etag
    100% |████████████████████████████████| 1.9MB 142kB/s
  Running setup.py (path:/tmp/pip-build-H9P8A1/gevent/setup.py) egg_info for package gevent
    Running command python setup.py egg_info
    WARNING: CFFI version 1.3.0 is required to build CFFI backend
    running egg_info
    creating pip-egg-info/gevent.egg-info
    writing requirements to pip-egg-info/gevent.egg-info/requires.txt
    writing pip-egg-info/gevent.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/gevent.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/gevent.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/gevent.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/gevent.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching '*/__pycache__'
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching 'config.log' found anywhere in distribution
    warning: no previously-included files matching 'config.status' found anywhere in distribution
    no previously-included directories found matching 'doc/_build'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.coverage' found under directory 'greentest'
    no previously-included directories found matching 'greentest/htmlcov'
    warning: no previously-included files matching 'stamp-h?' found under directory 'c-ares'
    warning: no previously-included files matching 'ares_build.h.orig' found under directory 'c-ares'
    no previously-included directories found matching 'libev/.deps'
    warning: no previously-included files matching 'Makefile' found under directory 'libev'
    warning: no previously-included files matching 'libtool' found under directory 'libev'
    warning: no previously-included files matching 'stamp-h?' found under directory 'libev'
    warning: no previously-included files matching 'config.h' found under directory 'libev'
    warning: no previously-included files matching '_corecffi.c' found under directory 'gevent'
    warning: no previously-included files found matching 'Makefile'
    writing manifest file 'pip-egg-info/gevent.egg-info/SOURCES.txt'

    WARNING: The gevent.ares extension has been disabled.
  Source in /tmp/pip-build-H9P8A1/gevent has version 1.1rc5, which satisfies requirement gevent from https://pypi.python.org/packages/source/g/gevent/gevent-1.1rc5.tar.gz#md5=0be79bda129e4091d4fc72b8d7a54528
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.9 in /usr/lib/python2.7/site-packages (from gevent)
Installing collected packages: gevent
  Running setup.py install for gevent ...     Running command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-H9P8A1/gevent/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1VpTza-record/install-record.txt --single-version-externally-managed --compile
    WARNING: CFFI version 1.3.0 is required to build CFFI backend
    running install
    running build
    running build_py
    creating build
    creating build/lib.cygwin-2.4.1-i686-2.7
    creating build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/backdoor.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/baseserver.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/builtins.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/core.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/corecffi.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/coros.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/event.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/fileobject.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/greenlet.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/hub.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/local.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/lock.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/monkey.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/os.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/pool.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/pywsgi.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/queue.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/resolver_ares.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/resolver_thread.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/select.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/server.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/signal.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/socket.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/ssl.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/subprocess.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/thread.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/threading.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/threadpool.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/timeout.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/util.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/win32util.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/wsgi.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_corecffi_build.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_fileobjectcommon.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_fileobjectposix.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_semaphore.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_socket2.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_socket3.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_socketcommon.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_ssl2.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_ssl3.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_sslgte279.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_tblib.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_threading.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/_util_py2.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    copying gevent/__init__.py -> build/lib.cygwin-2.4.1-i686-2.7/gevent
    running build_ext
    Running '(cd  "/tmp/pip-build-H9P8A1/gevent/libev"  && /bin/sh ./configure   && cp config.h "$OLDPWD" ) > configure-output.txt' in /tmp/pip-build-H9P8A1/gevent/build/temp.cygwin-2.4.1-i686-2.7/libev
```
Anyway I can fix it somehow or debug it more ?

**Comment by jamadden** [comment] 2016-02-28 16:18
I would suggest running that last command manually (i.e., the libev configure script) and seeing what output you get. 

Did this work with gevent 1.0? We don't officially test on Windows+cygwin so I have no idea if anything actually works there.

**Comment by ddorian** [comment] 2016-02-28 17:16
gevent 1.0 has the same issue.

That command (on both versions) hangs on :::

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling...

**Comment by jamadden** [comment] 2016-02-28 17:21
I'm sorry, I don't know what to tell you. cygwin is outside my area of expertise. However, the fact that at least one other user just installed gevent 1.0 into a cygwin environment suggests that the problem is system-dependent, so you might do the usual troubleshooting steps for that kind of thing: check environment variables, un-install/re-install, etc.

**Comment by jamadden** [comment] 2016-03-09 14:12
Issue #763 also has someone successfully using gevent or cygwin with python 2.7.

At this time, I think we have to consider this a local environment problem, so I'm going to close this issue. Please feel free to re-open it if you disagree, and please consider adding a comment when you figure out the problem in case anyone else runs into a similar issue.

**Closed by jamadden** 2016-03-09 14:12 UTC
Labels: invalid (environment or otherwise not a gevent issue)
