### ISSUE TITLE
AssertionError at install time 1.1rc2 with PyPy 4.0.1

### ISSUE THREAD

**Issue by fasaxc** [gevent/gevent#703] opened 2015-12-16 09:11 UTC
Installing 1.1rc2 into a fresh PyPy 4.0.1 virtualenv on Ubuntu 14.04 I get this assertion:
```
 Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-RI6Q6V/gevent/setup.py", line 498, in <module>
      run_setup(ext_modules, run_make=run_make)
    File "/tmp/pip-build-RI6Q6V/gevent/setup.py", line 484, in run_setup
      **setup_kwds
    File "/usr/lib/pypy/lib-python/2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/pypy/lib-python/2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/pypy/lib-python/2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pypyenv/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/tmp/pypyenv/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/tmp/pypyenv/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
```
The install seems to complete normally after that.

1.1b6 doesn't seem to show the same issue.
```
$ pypy --version
Python 2.7.10 (4.0.1+dfsg-1~ppa1~ubuntu14.04, Nov 20 2015, 19:34:15)
[PyPy 4.0.1 with GCC 4.8.4]
```

**Comment by jamadden** [comment] 2015-12-16 11:38
Installation probably worked because if `pip` can't build a wheel, it installs an egg instead. This looks like probably a bug in `pip` and/or `wheel`---I haven't encountered any issue when building 1.1rc2 wheels for other platforms (OS X/Windows). What version of `pip` and `wheel` are in that virtualenv? Can they be updated?

**Comment by jamadden** [comment] 2015-12-16 12:55
I don't reproduce this on Ubuntu 15.04 using the latest pip (7.1.2) and wheel (0.26).

**Comment by jamadden** [comment] 2016-01-04 12:54
I was able to reproduce this on OS X with CPython 3.5 and wheel 0.24. As soon as I upgrade to wheel 0.26, the problem goes away. Closing this as a wheel issue.

**Closed by jamadden** 2016-01-04 12:54 UTC

**Comment by jamadden** [comment] 2016-01-05 15:59
Discussion on IRC also indicates that the PPA packaged PyPy breaks the assumptions that wheel makes; I was using the version downloaded from pypy.org instead with success, and IRC reports the same.
