### ISSUE TITLE
Bogus timeout supplied to kevent calls

### ISSUE THREAD

**Issue by yurivict** [gevent/gevent#1051] opened 2017-12-09 08:12 UTC
The problem: the application using gevent, zeronet, freezes during startup after system boot. Subsequent runs usually succeed.

Tracing the problem with truss system call tracer shows that gevent passes a large and unreasonable timeout value to kevent in the freezing cases:
```kevent(17,{ 18,EVFILT_READ,EV_ADD|EV_ENABLE,0x0,0x0,0x0 },1,0x8023e8800,64,{ 59.743000000 }) ERR#4 'Interrupted system call'```

The same call in the succeeding case gets zero timeout:
```kevent(17,{ 18,EVFILT_READ,EV_ADD|EV_ENABLE,0x0,0x0,0x0 },1,{ },64,{ 0.000000000 }) = 0 (0x0)```

For some reason, gevent passes large timeout in some cases and this causes application to freeze.
gevent-1.2.2
python-2.7
ZeroNet-0.6.0
FreeBSD 11.1

All packages are installed from the FreeBSD ports.

**Comment by jamadden** [comment] 2017-12-09 11:56
gevent does not directly call kevent, libev does. libev is in charge of calculating timeouts, gevent does not *directly* influence that; all it can do is install timers that would *shorten* the amount of time libev will block in the system poll call. 


The fact that you see this change after boot is interesting. It suggests to me something unstable in the system or whatever resources the application uses. I have no idea what 'zeronet' is, but I'm going to guess something to do with networking, so the instability could be in what network interfaces or services are available---apparently none, leading it to not need to actually poll on anything. The value you're seeing for the timeout (`59.743`, which is neither unreasonable nor bogus) is *exactly* the value of [`MAX_BLOCKTIME`](http://cvs.schmorp.de/libev/ev.c?revision=1.481&view=markup#l486), the time that libev will use when there are no file/socket descriptors or timers to watch. So this apparent "hang" looks strongly like it could simply be a race condition, with zeronet starting up before whatever it's supposed to watch does, leading it to have nothing to watch. I suggest checking your startup order and delaying zeronet's startup until after its dependencies. (Alternately, just wait the 59 seconds and maybe zeronet will notice that what it's looking for is available for the next loop---if not, that's possibly a bug in zeronet.)

EINTR isn't usually a problem in a well designed application. The event loop will just cycle again allowing idle greenlets to run---this is where the application would detect external state changes such as a resource becoming available.

You could try using a different libev backend (though I wouldn't really expect that to make a difference).

As a long shot, from what I can tell, the freebsd port [disables gevent's typical use of libev](https://github.com/freebsd/freebsd-ports/blob/3608d272684f1e3c44476a5da4607c51bd271204/devel/py-gevent/Makefile), instead relying on an old [system library](https://github.com/freebsd/freebsd-ports/blob/d7cb557b47478b4047ff701030e9309f957ab6b2/devel/libev/Makefile).  That has been known to cause problems before, so you could try installing gevent from source using its default settings (`pip install gevent`) and running your application that way.

**Comment by yurivict** [comment] 2017-12-09 15:47
> As a long shot, from what I can tell, the freebsd port disables gevent's typical use of libev, instead relying on an old system library. That has been known to cause problems before, so you could try installing gevent from source using its default settings (pip install gevent) and running your application that way.

No, it relies on libev port that is supposed to be up to date.

**Comment by jamadden** [comment] 2017-12-09 16:00
> No, it relies on libev port that is supposed to be up to date.

According to the mirror I linked to, it is *not* up to date (although the documented changes should be inconsequential; but the documented changes don't always tell the full story).

But that's only part of the point. The very act of not embedding libev statically into the extension the way it's "meant" to be but instead linking to a system library changes things: the build is different, from C preprocessor macros down to things like LTO, all of which can expose behaviour differences.

As I said, though, it would be a long shot if your race condition was caused by that, but if you have nothing else to try that's something to remember.

**Comment by yurivict** [comment] 2017-12-09 17:04
Thanks for your analysis!

I requested the version update.https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224211

I will retest it and close if this fixes the problem.

**Comment by jamadden** [comment] 2017-12-09 17:05
> I will retest it and close if this fixes the problem.

I continue to doubt that it will. This looks much more like a race condition in the application and its dependencies.

**Comment by jamadden** [comment] 2018-01-31 15:44
There've been no updates in two months, and a bug was opened upstream. I'm going to go ahead and close this for now. Feel free to reopen if there are additional details.

**Closed by jamadden** 2018-01-31 15:44 UTC
Labels: POSIX, invalid (environment or otherwise not a gevent issue), libev, question
