### ISSUE TITLE
Possible memory leak with track_greenlet_tree=True

### ISSUE THREAD

**Issue by champax** [gevent/gevent#1467] opened 2019-10-01 07:00 UTC
* gevent version: gevent==1.4.0
* Python version: Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 8.3.0] on linux2
* Operating System: Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64 GNU/Linux

### Description:

Possible memory leak with track_greenlet_tree=True when a method spawn_later itself.
This leads to _spawning_stack_frames extending unbound, high cpu usage, high memory usage.

Workaround : track_greenlet_tree=False

I open this bug because i am not sure this behavior is intended, and more over, track_greenlet_tree is True by default.

### Repro:
```python
import gevent
from gevent import monkey, config

monkey.patch_all(aggressive=True)


class Test(object):
    """
    Test
    """

    # Current greenlet
    CUR_G = None

    # noinspection PyProtectedMember
    @classmethod
    def do_something(cls):
        """
        Do something async
        """

        if cls.CUR_G and cls.CUR_G._spawning_stack_frames:
            print("Called, len._spawning_stack_frames=%s, CUR_G=%s" % (len(cls.CUR_G._spawning_stack_frames), cls.CUR_G))
        else:
            print("Called, None")

        cls.CUR_G = gevent.spawn_later(0.5, cls.do_something)


if __name__ == '__main__':
    # Default is True
    config.track_greenlet_tree = True

    # Start
    Test.CUR_G = gevent.spawn_later(0.5, Test.do_something)

    # Run forever
    while True:
        gevent.sleep(100)

```

**Comment by jamadden** [comment] 2020-01-15 19:27
Thanks for the report. This is a duplicate of https://github.com/gevent/gevent/issues/1371 which is fixed in gevent 1.5.

**Closed by jamadden** 2020-01-15 19:27 UTC
