### ISSUE TITLE
Tracebacks in resolver threadpool are noisy (v1.1.b1)

### ISSUE THREAD

**Issue by parasyte** [gevent/gevent#617] opened 2015-07-18 03:11 UTC
Easy to reproduce with PyPy 2.6:

```python
import gevent.monkey
gevent.monkey.patch_all()

import urllib2

try:
    urllib2.urlopen("http://nxdomain/").read()
except:
    pass
```

A traceback is printed to the console from the resolver greenlet, and cannot be silenced?

```
Traceback (most recent call last):
  File "/Users/jay/projects/pubnub-auth/env-auth-pypy/site-packages/gevent/threadpool.py", line 203, in _worker
    value = func(*args, **kwargs)
gaierror: [Errno 8] nodename nor servname provided, or not known
(<ThreadPool at 0x107d53a60 0/1/10>, <built-in function getaddrinfo>) failed with gaierror
```

**Comment by jamadden** [comment] 2015-07-18 03:26
Yes, that's true. The threadpool works just like greenlets and the hub: uncaught errors are printed. I don't believe this is new. There's another issue about that somewhere...

**Comment by parasyte** [comment] 2015-07-18 03:33
Right, perhaps #83?

**Comment by jamadden** [comment] 2015-07-18 03:37
I was thinking of #137 but yeah that one too I guess.

**Comment by jamadden** [comment] 2015-07-18 13:19
Closing as duplicate of #83 and/or #137, which have more discussion. The mentions in the comments here will ensure that threadpool is also noted on those issues.

**Closed by jamadden** 2015-07-18 13:19 UTC
Labels: duplicate, enhancement
