### ISSUE TITLE
Python 3.8.6 and perhaps other recent Python 3.8 builds are incompatible

### ISSUE THREAD

**Issue by AaronFriel** [gevent/gevent#1679] opened 2020-09-25 01:34 UTC
* gevent version: 1.4.0
* Python version: Please be as specific as possible: the `python:3.8` docker image as of 2020-09-24 6:30PM PST
* Operating System: Linux - ubuntu or Docker on Windows or Docker on Mac or Google container optimized linux

### Description:

Trying to boot a gunicorn worker with `--worker-class=gevent` and it logs this and then infinite loops:

```<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
[2020-09-25 01:13:02 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2020-09-25 01:13:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2020-09-25 01:13:02 +0000] [1] [INFO] Using worker: gevent
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2020-09-25 01:13:02 +0000] [7] [INFO] Booting worker with pid: 7
[2020-09-25 01:13:02 +0000] [7] [INFO] Made Psycopg2 Green
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2020-09-25 01:13:02 +0000] [8] [INFO] Booting worker with pid: 8
[2020-09-25 01:13:02 +0000] [8] [INFO] Made Psycopg2 Green
/usr/local/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2020-09-25 01:13:02 +0000] [9] [INFO] Booting worker with pid: 9
[2020-09-25 01:13:02 +0000] [9] [INFO] Made Psycopg2 Green
# infinite loop
```

**Comment by AaronFriel** [comment] 2020-09-25 01:55
Updating to gevent `20.9.0` resolves the issue.

**Comment by jamadden** [comment] 2020-09-25 10:25
Duplicate of #1678. 

If you use Python 3.7 or above, you must use greenlet 0.4.17 with gevent 20.9.0; do not update greenlet independently of gevent. Or use greenlet 0.4.16 with gevent 20.6.x.

**Closed by jamadden** 2020-09-25 10:25 UTC
