### ISSUE TITLE
Fix #190 misses the "r+" case

### ISSUE THREAD

**Issue by vitaly-krugl** [gevent/gevent#203] opened 2012-11-13 21:49 UTC
Fix #190: "Do not flush FileObjectThread if in read mode" takes care of "if 'w' in mode or 'a' in mode", but misses the "r+" case.  This relates to commit b99ab3c5aeaf484d62e7daf1c884cda8f5dc859f:

```
# NOTE: the file being opened with "r+" must already exist before the open call
In [53]: f = open("zzz", "r+")

In [54]: f.mode
Out[54]: 'r+'

In [55]: f.flush()


In [56]: 
```

That said, I think that we could remove self.flush() from FileObjectThread.close method altogether: if FileObjectThread was instantiated with close=True (default), then we expect fobj.close() to flush it automatically, if it deems it necessary. However, if FileObjectThread was instantiated with close=False (the non-file-descriptor case), then the user is retaining control of the underlying fobj and can flush it if/when needed or when it's time to close the fobj.

mode may be the following strings (from 'man fopen'):
```
     ``r''   Open text file for reading.  The stream is positioned at the
             beginning of the file.

     ``r+''  Open for reading and writing.  The stream is positioned at the
             beginning of the file.

     ``w''   Truncate to zero length or create text file for writing.  The
             stream is positioned at the beginning of the file.

     ``w+''  Open for reading and writing.  The file is created if it does not
             exist, otherwise it is truncated.  The stream is positioned at
             the beginning of the file.

     ``a''   Open for writing.  The file is created if it does not exist.  The
             stream is positioned at the end of the file.  Subsequent writes
             to the file will always end up at the then current end of file,
             irrespective of any intervening fseek(3) or similar.

     ``a+''  Open for reading and writing.  The file is created if it does not
             exist.  The stream is positioned at the end of the file.  Subse-
             quent writes to the file will always end up at the then current
             end of file, irrespective of any intervening fseek(3) or similar.
```

**Comment by jamadden** [comment] 2015-07-14 00:27
I am unable to reproduce the error mentioned in the original bug report on any supported version of Python on OS X or Linux (I added a test case), so I'm going to go ahead and close this. Please feel free to reopen if it still occurs for you with 1.1/master.

**Closed by jamadden** 2015-07-14 00:27 UTC
