### ISSUE TITLE
gevent threadpool error: can't start new thread

### ISSUE THREAD

**Issue by emamirazavi** [gevent/gevent#569] opened 2015-06-07 15:24 UTC
My code is working 2 days permanently without any problem, but suddenly:

```
    rss_robot_cron()
  File "/usr/local/src/***/lib/myapp/rss_robot.py", line 163, in cron
    feed_all()
  File "/usr/local/src/***/lib/myapp/rss_robot.py", line 154, in feed_all
    pool.spawn(rssdownloader, rssbot)
  File "/usr/lib64/python2.7/site-packages/gevent/threadpool.py", line 159, in spawn
    self.adjust()
  File "/usr/lib64/python2.7/site-packages/gevent/threadpool.py", line 133, in adjust
    self._adjust_step()
  File "/usr/lib64/python2.7/site-packages/gevent/threadpool.py", line 113, in _adjust_step
    self._add_thread()
  File "/usr/lib64/python2.7/site-packages/gevent/threadpool.py", line 142, in _add_thread
    start_new_thread(self._worker, ())
error: can't start new thread
```
Can anybody help me about these errors to solve?

**Comment by emamirazavi** [comment] 2015-06-07 15:32
gevent version is 1.0.1

**Comment by emamirazavi** [comment] 2015-06-07 15:35
And my python code to use gevent threadpool:

```
def feed_all():
    datenow = datetime.now()
    rq = RawQuery(RssRobot, """SELECT * FROM rssrobot WHERE status = %s and watch_start_time <= %s and 
        watch_end_time > %s and (last_created is NULL or date_add(last_created, INTERVAL watch_period hour) < %s)""", 
        '1', datenow.time(), datenow.time(), datenow)
    logger.debug('rss_feeder called, raw query returns: %s' % rq)
      rssbot = None
    pool = ThreadPool(CONCURRENT_RSS_DL)
    for rssbot in rq.execute():
        logger.debug('rss_feeder rss found to feed: %s' % rssbot)
        pool.spawn(rssdownloader, rssbot)
    else:
        if not rssbot:
            logger.debug('No RSS to parse!')
      if pool.size:
        gevent.wait()
    
    my_db.close()
    
def cron():
    feed_all()
```

cron method would be called every 5 minutes.

**Comment by jamadden** [comment] 2015-06-07 17:22
That error is raised by the underlying Python library when it is unable to start a native (OS) thread. gevent is simply letting it percolate up. The underlying problem will depend on the platform. One common cause for not being able to start a new thread is having too many threads running already or otherwise having a memory layout such that  the stack space for the new thread cannot be allocated. Perhaps the repeated invocations are starting threads that are never finishing?

**Comment by emamirazavi** [comment] 2015-06-07 23:31
Thanks, perhaps, but it's very distant. Because in every 5 minutes my code
run and if gevent.wait() is not released i will not have any cycle and
repeated run in my cron, of course my cron is running on time. I should see
my code more carefully. I think it's a good idea if I create threadpool
instance in my cron thread and pass it to the feed function to avoid extra
creation of threadpool. I suspicious to memory more than exceeding count of
thread. After all, my resources in this VPS with CentOS 7 is limited to 1
GB of RAM and 1 core of CPU. gevent.wait() should assure end of all pooled
thread, should not it?!

**Comment by jamadden** [comment] 2015-06-08 00:37
I suspect that if you want to wait for all the tasks in the threadpool to finish, you should use `pool.join`. `gevent.wait` operates on the current event loop, and, IIRC, each new thread gets its own event loop and so the `pool` itself would be unaffected. I'm not deeply familiar with the interactions so I could be wrong about the specifics, but `pool.join` is a more explicit, idiomatic, way of accomplishing the goal of waiting for all the tasks in the pool to finish.

**Comment by emamirazavi** [comment] 2015-06-08 03:27
Thanks jamadden, i think your assumption is right! Apparently gevent.wait is suitable to use in each event loop or to wait for some specific type of gevent modules like: gevent.Greenlet, gevent.event.Event, gevent.lock.Semaphore and gevent.subprocess.Popen. see http://www.gevent.org/gevent.html#gevent.wait
I think gevent.threadpool is not included in these type of instances. is it?

**Comment by emamirazavi** [comment] 2015-06-10 12:00
@jamadden see this url: https://github.com/gevent/gevent/blob/master/examples/threadpool.py and note to the gevent.wait. What is your opinion?

**Comment by emamirazavi** [comment] 2015-06-10 12:31
problem is related to new ThreadPool.
new ThreadPool for each package of threads is incorrect.
this is right:
<pre>
import gevent
from gevent.threadpool import ThreadPool
from random import random
from time import sleep

CONCURRENT = 100

def test(arg1, arg2, arg3):
	print('test %d/%d started' % (arg3, arg2))
	sleep(int(arg1 * 20))
	print('test %d/%d ended' % (arg3, arg2))

pool = ThreadPool(CONCURRENT)

def testpool(npool, count):
	print('')
	print('threadpool %d started.' % count)
	# pool = ThreadPool(CONCURRENT)
	for i in range(1, int(random() * 200)):
		npool.spawn(test, random(), count, i)
	print('threadpool %d joined.' % count)
	npool.join()
	print('threadpool %d done.' % count)

counter = 0

while 1:
	counter += 1
	# start to testpool
	testpool(pool, counter)
	# sleep 
	sleep(0.3)
</pre>

and this goes to hill:
<pre>
import gevent
from gevent.threadpool import ThreadPool
from random import random
from time import sleep

CONCURRENT = 100

def test(arg1, arg2, arg3):
	print('test %d/%d started' % (arg3, arg2))
	sleep(int(arg1 * 20))
	print('test %d/%d ended' % (arg3, arg2))

pool = ThreadPool(CONCURRENT)

def testpool(count):
	print('')
	print('threadpool %d started.' % count)
	npool = ThreadPool(CONCURRENT)
	for i in range(1, int(random() * 200)):
		npool.spawn(test, random(), count, i)
	print('threadpool %d joined.' % count)
	npool.join()
	print('threadpool %d done.' % count)

counter = 0

while 1:
	counter += 1
	# start to testpool
	testpool(pool, counter)
	# sleep 
	sleep(0.3)
</pre>

**Comment by pigmej** [comment] 2015-06-10 12:41
@emamirazavi 

In your 'broken' code, you want to start 0 or 200 threads every 0.3 seconds (on 100 thread pool). It's just above your system limits, it's not gevent fault at all.

Also I'm just curious, why are you using ThreadPool for download/parse RSS ?

**Comment by emamirazavi** [comment] 2015-06-10 13:52
@pigmej 
Please at first run the code and after that give me your opinion about gevent. Gevent supports this example very very good and this is just an example to use ThreadPool correctly. I have added this issue and i solved it and expose it's solution.
Also for RSS downloader/parser: sometimes you may have 100,000 RSS url to parse and want to trace all of them every 5 minutes. It's a good idea if you create a pool of RSS downloader and make downloading and parsing faster. If you want download them one after other, you can do.

**Comment by pigmej** [comment] 2015-06-10 14:29
@emamirazavi I doesn't wanted to be rude or something.

The thing is with gevent you don't need to do it with threadpool, threadpool is for things that requires REAL OS thread. Gevent has lightweight threads (with monkeypatch its ~1:1 API). Your job "fetching 100 000 RSS" is perfect for gevent lighweight threads, because they are perfect for IO operations (network, disk whatever).

To download it faster then just create Gevent Pool. I really think you don't need ThreadPool there at all.

**Comment by emamirazavi** [comment] 2015-06-10 16:21
@pigmej I have a little limitation to use gevent.pool in my code.
I can not remember exactly. But i use asyncore in my code and some other things and when i studied about monkey.patch... i saw several pains with some other packages. for example in pooling you must use gevent.sleep not time.sleep or when you are using requests.get you can not run it with other requests.get. see this:
```
import gevent
from gevent import monkey
from time import sleep
from gevent import pool
import requests

monkey.patch_all()

p = pool.Pool(3)
def t(id, delay):
	print('starting t, id: %d, delay: %d' % (id, delay))
	r = requests.get('http://www.theguardian.com/uk')
        print('downloaded text, id: %d, text: %s' % (id, r.text[0:50]))
        # gevent.sleep(delay)
	print('ending t, id: %d' % id)

p.spawn(t, 1, 10)
p.spawn(t, 2, 10)
p.join()
```
If you don't use monkey you can not do your work so that i want. ThreadPool is a new feature in new Gevent and programmers of it should tell us the philosophy to create it. @jamadden can you tell me if i'm wrong to use ThreadPool in these examples?

**Comment by pigmej** [comment] 2015-06-10 16:52
ThreadPool is not new at all.

First of all, you have to monkeypatch asap, you patch after importing requests. At short this will mean that all requests code (sockets inside to be precise) will block gevent. Same applies for your "polling issue" (time.sleep vs gevent.sleep).

Also, ThreadPool in gevent is "nothing" more/less than wrapper that allows you to execute code in other OS thread, the real heavy thread.
In short it works like this: in thread where you "spawn" functions + arguments, both are added to Queue (from threading module), then your "other thread" can get (blocking) the task (function + args), then result is sent back (wrapped in AsyncResult from gevent side afair), and "that's it".

If you want high concurrency with gevent, then DO NOT use threadpool, if you want to use threadpool "by design" then use normal threading module, because you benefit nothing.

Also most of modern systems are limiting number of os threads than single useer can create. This limit obviously is not for greenlets.

When you need threadpool in gevent?
* when you need to wrap some C code which is not gevent friendly (current cares resolver for example)
* probably that's all, python has GIL, so threading to use more cores makes no sense (except when you release it "somehow").


For your task, just use gevent.Pool and you will be fine (and mokenypatch ASAP - first two lines of your python file import + patch).

-----Original Message-----

**Comment by emamirazavi** [comment] 2015-06-10 21:10
Thanks a lot @pigmej for your expanded answer. If i have no problem with patch... i will use it instead of ThreadPool sure.

**Comment by emamirazavi** [comment] 2015-06-26 11:04
@pigmej see this https://github.com/benoitc/gunicorn/issues/1056 start of using everything except ThreadPool and calling monkey.patch_all. My app crashed since some days ago.

**Comment by pigmej** [comment] 2015-06-26 11:45
@emamirazavi ??

I really don't get you. You still don't see a difference between ThreadPool and gevent.Pool. Those are 2 different things, and those are used for completely different reasons.

You're trying to use ThreadPool incorrectly, where you really should use gevent.Pool.

That error is certainly fail in your application logic. You just hit SYSTEM threads limit, it's not gevent fault that you want to spawn too many SYSTEM threads (and you did it explicit, by using ThreadPool incorrectly).

@jamadden this should be really closed.

**Comment by jamadden** [comment] 2015-06-26 22:52
I agree that there seems to be some confusion on what the actual issue is, if indeed there is an issue, or just a misunderstanding on how gevent is designed and intended to be used. It also seems that the discussion in this issue has diverged from the original report, which, as far as I can see, was solved through a good discussion. 

In the interest of keeping issue reports targeted and the discussion on topic, and to help prevent frustrations from arising when that starts to go awry, I think it's probably best to close this issue again. 

Please open a new issue if there are specific problems with gevent to discuss. Or, for more general help, try asking on the mailing list.

Remember, this is a community of volunteers and people just trying to get things done, all of us with different skill and experience levels. I know it can be frustrating when it seems a point isn't getting across, but I also know that we can all act with respect towards each other.

**Closed by jamadden** 2015-06-26 22:52 UTC
