### ISSUE TITLE
pywsgi.py with SSE produces extraneous TCP packets

### ISSUE THREAD

**Issue by tomberek** [gevent/gevent#1233] opened 2018-06-02 21:05 UTC
* gevent version: 1.2.2
* Python version: Python 2.7.14
* Operating System: Ubuntu x86_64

### Description:
Using various versions of SSE (Server Side Events), for example from here: http://flask.pocoo.org/snippets/116/ with the pywsgi embedded server, running Wireshark shows multiple packets per server push. This is caused by:

https://github.com/gevent/gevent/blob/master/src/gevent/pywsgi.py#L724-L726

which itself is caused by never running https://github.com/gevent/gevent/blob/master/src/gevent/pywsgi.py#L698 . 

A browser will ignore the extra packets, but they are sent and processed anyway. I could not find an easy workaround by changing settings or headers. Using gunicorn to serve, rather than the build-in WSGIServer does not produce these extra packets.

**Comment by jamadden** [comment] 2018-06-02 23:45
Packets at the TCP level shouldn't matter, that's independent of the *stream* of data (i.e., what the browser sees is *above* the level of TCP). Other than slightly more overhead, is there some problem this causes?

**Comment by tomberek** [comment] 2018-06-04 11:08
No. But having three round trips per push negates much of the reason to use SSE. It’s quite a bit of overhead. A single conditional on the content-type could set the Boolean to not use chunked encoding.

**Comment by arcivanov** [comment] 2018-06-04 12:05
@jamadden would https://docs.python.org/3/library/socket.html#socket.socket.sendmsg help in this case?

**Comment by jamadden** [comment] 2018-06-15 18:31
I'll wait a few more days for additional discussion and feedback on this. If I don't hear anything my intent at this time is to close this as "known set of tradeoffs."

**Comment by tomberek** [comment] 2018-06-15 20:42
Simply exposing the `response_use_chunked` or similar boolean in some manner that allows traversal down the other side of the conditional would allow EventStream users to trim out the extra packets.

**Comment by jamadden** [comment] 2018-06-15 21:50
I don't think it's quite that simple 😄 . For one thing, without a `Content-Length` header or a `Transfer-Encoding: chunked` header, the only way for the client to know it's done expecting results is for the connection to close. To prevent it from trying to pipeline requests, the response should include the `Connection: close` header (and of course we should actually close the connection). Currently we don't have any way to detect and set that.

More seriously, without using `Transfer-Encoding: chunked`, the client doesn't necessarily have any way to know when it should present a buffer for reading to higher levels. TCP doesn't tell it. Strictly speaking neither does HTTP, of course, but exposing chunks seems to be a common and relied upon implementation strategy. Depending on fragmentation and socket buffers, intervening proxies, etc, a single message might wind up visible in a single `recv` call or multiple `recv` calls or multiple messages might get bundled into a single `recv` call.  

This effect of simply turning off `response_use_chunked`  is easy to see with a client like `httpie` if you use our earlier app, and add a sleep to slow it down between yields. Because httpie is waiting for the connection to close to know the message is done, you get: 

```console
$ http http://localhost:8080
HTTP/1.1 200 OK
Content-Type: text/plain
Date: Fri, 15 Jun 2018 21:14:20 GMT


http: error: ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Read timed out.
```

curl is architected differently and parses each incoming `recv` looking for newlines to display, but if you take those out of the example, it too hangs without displaying any output. (And without `Connection: close`, we wait for a second request to come, even after we've exhausted the iterable, and curl *still sits there.)

Now it's true that one specific (non-IANA-standard) MIME type (text/event-stream) mandates newline in message framing, but there's no way to know if clients for that MIME type are able to hook low-enough into the HTTP stream to be able to pull them out without actually using chunks. While the HTML living standard does recommend that browsers use an appropriate line-based buffering mode for that event type when constructing an `EventSource` object, there are definitely polyfills for otherwise unsupported browsers that have no access to that level and can't.

* I don't think gevent should provide any specific support for `text/event-stream` (neither does gunicorn). 
* Even so, it's somewhat more complicated than it looks to disable chunking because of the need to set the `Connection: close` header and actually close the connection. We can't rely on the WSGI app to do this.
* For the best buffering and proxy experience across all sorts of clients, I think that WSGI iterables *should* be sent using chunked encoding whenever possible.

That gets us back to the reason why this was requested in the first place, which was to reduce the number of `send` calls and the number of packets due to "quite a bit of overhead." My synthetic benchmarks didn't detect significant overhead from the three calls, and actually showed that to be more efficient than building a single buffer (which is the only remaining option). Thus the question that needs answered is, can this overhead be demonstrated or documented as being problematic in other benchmarks or real world uses, to the extent that it justifies whatever complexity is required to implement and test a different approach?

**Comment by jamadden** [comment] 2018-06-15 23:20
Other datapoints: gevent does *not* currently disable Nagle's algorithm  for its pywsgi sockets (call `sock.setsockopt(SOL_TCP, socket.TCP_NODELAY, 1)`. This means that we would typically expect small writes to accumulate *if* we are awaiting remote ACKs, thus gaining some buffering benefits at the kernel level. On a localhost, this would probably make a very small difference, but across a WAN it might make a larger difference in reducing the actual packets. (In local benchmarks I observed a 3-8% *drop* in performance from disabling Nagle. Since we're bottlenecked in Python, this makes sense. Disabling it resulted in an *increase* of the number of packets sent by 3%, again that makes sense.)

gunicorn *does* disable Nagle's algorithm, I believe.

There's also the platform-specific TCP_NOPUSH/TCP_CORK option, which explicitly allows multiple writes to be combined. It did indeed dramatically reduce the number of packets transmitted, by 3 orders of magnitude, at the cost of significant latency. It seems (on macOS anyway) once it is turned on it can't fully be turned off (at least for short lived streams).

Finally, **it looks like my first round of synthetic benchmarks may be largely invalid**.  I have to do some more checking, but I may not have been testing what I thought I was testing. If so, my apologies for putting everyone through all that. I will double check and if necessary run numbers again.

**Comment by jamadden** [comment] 2018-06-16 16:45
![image](https://user-images.githubusercontent.com/1256082/41500166-a0398ac0-7152-11e8-9c24-546ad29649df.png)

OK, above are more accurate numbers. The X axis is RPS on Python 3.6 with 10 clients and 200 requests. This does indeed show a small but constant overhead for a perfect network.

![image](https://user-images.githubusercontent.com/1256082/41500172-af7ad6e2-7152-11e8-82f5-17e929a1bcb9.png)

Likewise for a lossy network, there's a constant overhead. The TCP_NODELAY value is all over the place, though, with it apparently helping for non-chunked transfers on lossy networks but hurting for chunked, and the opposite on perfect networks. I didn't run any statistical regressions but I'd probably consider the difference in the margin of error. 

So with this new data, I think it's clear that the overhead is measurable in these synthetic benchmarks (whether its significant in a practical context is undetermined). The overhead does begin to vanish as chunk sizes increase; the lines meet at around 75000 bytes. I suspect most chunks are smaller than that. Based on this, it seems reasonable to me to *attempt* a combined write, as its not that hard and there may be benefits (I say attempt because `socket.sendall`, especially in gevent, calls `send` repeatedly, so a lot depends on the state of the buffers, congestion, window sizes, etc.).

Thanks for this conversation! Once again I apologise for drawing incorrect conclusions based on faulty data above.

**Closed** 2018-06-18 12:17 UTC
